#!/usr/bin/env bash
# Test: Watchtower static UI files — HTML structure, no external URLs, valid JS templates
set -euo pipefail

TEKHTON_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

PASS=0
FAIL=0

assert() {
    local label="$1"
    shift
    if "$@" 2>/dev/null; then
        PASS=$((PASS + 1))
    else
        echo "  FAIL: ${label}"
        FAIL=$((FAIL + 1))
    fi
}

assert_not() {
    local label="$1"
    shift
    if ! "$@" 2>/dev/null; then
        PASS=$((PASS + 1))
    else
        echo "  FAIL: ${label}"
        FAIL=$((FAIL + 1))
    fi
}

WATCHTOWER_DIR="${TEKHTON_HOME}/templates/watchtower"

# --- Test 1: Required files exist ---
assert "index.html exists" test -f "${WATCHTOWER_DIR}/index.html"
assert "style.css exists" test -f "${WATCHTOWER_DIR}/style.css"
assert "app.js exists" test -f "${WATCHTOWER_DIR}/app.js"

# --- Test 2: HTML basic structure ---
assert "HTML has DOCTYPE" grep -q '<!DOCTYPE html>' "${WATCHTOWER_DIR}/index.html"
assert "HTML has lang attribute" grep -q '<html lang="en">' "${WATCHTOWER_DIR}/index.html"
assert "HTML has charset" grep -q 'charset="UTF-8"' "${WATCHTOWER_DIR}/index.html"
assert "HTML has viewport meta" grep -q 'name="viewport"' "${WATCHTOWER_DIR}/index.html"
assert "HTML includes style.css" grep -q 'href="style.css"' "${WATCHTOWER_DIR}/index.html"
assert "HTML includes app.js" grep -q 'src="app.js"' "${WATCHTOWER_DIR}/index.html"

# --- Test 3: All 4 tab sections exist ---
assert "tab-live section" grep -q 'id="tab-live"' "${WATCHTOWER_DIR}/index.html"
assert "tab-milestones section" grep -q 'id="tab-milestones"' "${WATCHTOWER_DIR}/index.html"
assert "tab-reports section" grep -q 'id="tab-reports"' "${WATCHTOWER_DIR}/index.html"
assert "tab-trends section" grep -q 'id="tab-trends"' "${WATCHTOWER_DIR}/index.html"

# --- Test 4: Data file script tags ---
for datafile in run_state timeline milestones security reports metrics; do
    assert "data/${datafile}.js script tag" grep -q "src=\"data/${datafile}.js\"" "${WATCHTOWER_DIR}/index.html"
done

# --- Test 5: No external URLs in static files ---
for file in index.html style.css app.js; do
    assert_not "no http:// in ${file}" grep -qE 'https?://' "${WATCHTOWER_DIR}/${file}"
done

# --- Test 6: No CDN or external references ---
for file in index.html style.css app.js; do
    assert_not "no cdn in ${file}" grep -qi 'cdn\.' "${WATCHTOWER_DIR}/${file}"
    assert_not "no googleapis in ${file}" grep -qi 'googleapis' "${WATCHTOWER_DIR}/${file}"
    assert_not "no unpkg in ${file}" grep -qi 'unpkg' "${WATCHTOWER_DIR}/${file}"
done

# --- Test 7: HTML validates with xmllint if available ---
if command -v xmllint &>/dev/null; then
    # xmllint --html mode is lenient for HTML5
    if xmllint --noout --html "${WATCHTOWER_DIR}/index.html" 2>/dev/null; then
        PASS=$((PASS + 1))
    else
        echo "  FAIL: xmllint HTML validation"
        FAIL=$((FAIL + 1))
    fi
elif command -v tidy &>/dev/null; then
    # tidy returns 0 for clean, 1 for warnings, 2 for errors
    if tidy -quiet -errors "${WATCHTOWER_DIR}/index.html" 2>/dev/null; then
        PASS=$((PASS + 1))
    else
        # tidy exit 1 = warnings only (acceptable)
        ec=$?
        if [[ "$ec" -eq 1 ]]; then
            PASS=$((PASS + 1))
        else
            echo "  FAIL: tidy HTML validation"
            FAIL=$((FAIL + 1))
        fi
    fi
fi

# --- Test 8: JS data file templates generate valid syntax ---
# Simulate what dashboard_parsers.sh produces and verify JS parses
cat > "${TMPDIR}/test_data.js" << 'JSEOF'
// Generated by Tekhton Watchtower — do not edit
// Updated: 2026-01-01T00:00:00Z
window.TK_RUN_STATE = {"pipeline_status":"running","stages":{}};
JSEOF

if command -v node &>/dev/null; then
    assert "JS data template is valid" node -e "
        var fs = require('fs');
        var code = fs.readFileSync('${TMPDIR}/test_data.js', 'utf8');
        var window = {};
        eval(code);
        if (!window.TK_RUN_STATE) process.exit(1);
    "
fi

# --- Test 9: CSS has required responsive breakpoints ---
assert "CSS has 1200px breakpoint" grep -q '1200px' "${WATCHTOWER_DIR}/style.css"
assert "CSS has 768px breakpoint" grep -q '768px\|767px' "${WATCHTOWER_DIR}/style.css"

# --- Test 10: app.js has required render functions ---
assert "app.js has renderLiveRun" grep -q 'renderLiveRun' "${WATCHTOWER_DIR}/app.js"
assert "app.js has renderMilestoneMap" grep -q 'renderMilestoneMap' "${WATCHTOWER_DIR}/app.js"
assert "app.js has renderReports" grep -q 'renderReports' "${WATCHTOWER_DIR}/app.js"
assert "app.js has renderTrends" grep -q 'renderTrends' "${WATCHTOWER_DIR}/app.js"
assert "app.js has initTabs" grep -q 'initTabs' "${WATCHTOWER_DIR}/app.js"

# --- Test 11: app.js uses localStorage for tab persistence ---
assert "app.js uses localStorage" grep -q 'localStorage' "${WATCHTOWER_DIR}/app.js"

# --- Test 12: app.js handles empty TK_* globals ---
assert "app.js has TK_RUN_STATE fallback" grep -q 'TK_RUN_STATE || {}' "${WATCHTOWER_DIR}/app.js"
assert "app.js has TK_TIMELINE fallback" grep -q 'TK_TIMELINE || \[\]' "${WATCHTOWER_DIR}/app.js"

# --- Test 13: Size constraint (90KB total) ---
# Bumped from 75KB to 90KB for M37 parallel teams UI (team cards, group view, team trends)
total_size=0
for file in index.html style.css app.js; do
    fsize=$(wc -c < "${WATCHTOWER_DIR}/${file}")
    total_size=$((total_size + fsize))
done
assert "total static size under 90KB" test "$total_size" -lt 92160

# --- Test 14: _copy_static_files function exists in dashboard.sh ---
assert "_copy_static_files in dashboard.sh" grep -q '_copy_static_files' "${TEKHTON_HOME}/lib/dashboard.sh"

# --- Test 15: refresh_interval_ms in dashboard.sh ---
assert "refresh_interval_ms in dashboard.sh" grep -q 'refresh_interval_ms' "${TEKHTON_HOME}/lib/dashboard.sh"

# --- Test 16: CSS has dark theme variables ---
assert "CSS has dark theme vars" grep -q '\-\-bg-primary' "${WATCHTOWER_DIR}/style.css"
assert "CSS has prefers-color-scheme" grep -q 'prefers-color-scheme' "${WATCHTOWER_DIR}/style.css"

# --- Test 17: Causal trace support ---
assert "app.js has causal trace" grep -q 'causal-highlight\|getCausalChain\|causalChildren' "${WATCHTOWER_DIR}/app.js"

# --- Test 18: Actions tab (M36) ---
assert "HTML has Actions tab button" grep -q 'data-tab="actions"' "${WATCHTOWER_DIR}/index.html"
assert "HTML has Actions tab section" grep -q 'id="tab-actions"' "${WATCHTOWER_DIR}/index.html"
assert "HTML includes inbox.js" grep -q 'data/inbox.js' "${WATCHTOWER_DIR}/index.html"
assert "app.js has renderActions" grep -q 'renderActions' "${WATCHTOWER_DIR}/app.js"
assert "app.js has TK_INBOX fallback" grep -q 'TK_INBOX' "${WATCHTOWER_DIR}/app.js"
assert "app.js has submitFile" grep -q 'submitFile' "${WATCHTOWER_DIR}/app.js"
assert "app.js has server probe" grep -q 'probeServer\|/api/ping' "${WATCHTOWER_DIR}/app.js"
assert "CSS has action-card styles" grep -q 'action-card' "${WATCHTOWER_DIR}/style.css"
assert "CSS has form-group styles" grep -q 'form-group' "${WATCHTOWER_DIR}/style.css"

# --- Test 19: inbox.js seed in dashboard.sh ---
assert "dashboard.sh seeds inbox.js" grep -q 'inbox.js' "${TEKHTON_HOME}/lib/dashboard.sh"

# --- Test 20: emit_dashboard_inbox in emitters ---
assert "emit_dashboard_inbox exists" grep -q 'emit_dashboard_inbox' "${TEKHTON_HOME}/lib/dashboard_emitters.sh"

# --- Test 21: inbox.sh exists and sources ---
assert "inbox.sh exists" test -f "${TEKHTON_HOME}/lib/inbox.sh"
assert "inbox.sh has process_watchtower_inbox" grep -q 'process_watchtower_inbox' "${TEKHTON_HOME}/lib/inbox.sh"
assert "tekhton.sh sources inbox.sh" grep -q 'source.*inbox.sh' "${TEKHTON_HOME}/tekhton.sh"

# --- Test 22: Parallel teams support (M37) ---
assert "dashboard.sh has parallel_mode" grep -q 'parallel_mode' "${TEKHTON_HOME}/lib/dashboard.sh"
assert "dashboard.sh has emit_dashboard_team_state" grep -q 'emit_dashboard_team_state' "${TEKHTON_HOME}/lib/dashboard.sh"
assert "app.js has team-cards-row" grep -q 'team-cards-row' "${WATCHTOWER_DIR}/app.js"
assert "app.js has parallel_mode detection" grep -q 'parallel_mode' "${WATCHTOWER_DIR}/app.js"
assert "app.js has renderMilestonesByGroup" grep -q 'renderMilestonesByGroup' "${WATCHTOWER_DIR}/app.js"
assert "app.js has renderTeamPerformance" grep -q 'renderTeamPerformance' "${WATCHTOWER_DIR}/app.js"
assert "app.js has team filter" grep -q 'team-filter-btn\|activeTeamFilter' "${WATCHTOWER_DIR}/app.js"
assert "app.js has report team selector" grep -q 'report-team-selector\|activeReportTeam' "${WATCHTOWER_DIR}/app.js"
assert "CSS has team-card styles" grep -q 'team-card' "${WATCHTOWER_DIR}/style.css"
assert "CSS has ms-view-toggle" grep -q 'ms-view-toggle' "${WATCHTOWER_DIR}/style.css"
assert "CSS has cross-deps-summary" grep -q 'cross-deps-summary' "${WATCHTOWER_DIR}/style.css"
assert "CSS has report-team-selector" grep -q 'report-team-selector' "${WATCHTOWER_DIR}/style.css"
assert "finalize_summary.sh has team field" grep -q '"team"' "${TEKHTON_HOME}/lib/finalize_summary.sh"
assert "finalize_summary.sh has parallel_group field" grep -q '"parallel_group"' "${TEKHTON_HOME}/lib/finalize_summary.sh"
assert "finalize_summary.sh has concurrent_teams field" grep -q '"concurrent_teams"' "${TEKHTON_HOME}/lib/finalize_summary.sh"
assert "emitters has per-team reports" grep -q 'teams_reports_json' "${TEKHTON_HOME}/lib/dashboard_emitters.sh"

# --- Summary ---
echo "watchtower_html: ${PASS} passed, ${FAIL} failed"
[[ "$FAIL" -eq 0 ]]
