#!/usr/bin/env bash
# Test: Dashboard data emission (lib/dashboard.sh, lib/dashboard_parsers.sh)
set -euo pipefail

TEKHTON_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

# --- Minimal stubs -----------------------------------------------------------
PROJECT_DIR="$TMPDIR"
TIMESTAMP="20260315_100000"
LOG_DIR="${TMPDIR}/.claude/logs"
DASHBOARD_DIR=".claude/dashboard"
DASHBOARD_ENABLED=true
DASHBOARD_VERBOSITY=normal
DASHBOARD_HISTORY_DEPTH=50
DASHBOARD_MAX_TIMELINE_EVENTS=500
DASHBOARD_REFRESH_INTERVAL=10
CAUSAL_LOG_ENABLED=true
CAUSAL_LOG_FILE="${TMPDIR}/.claude/logs/CAUSAL_LOG.jsonl"
CAUSAL_LOG_MAX_EVENTS=2000
CAUSAL_LOG_RETENTION_RUNS=50

mkdir -p "$LOG_DIR"

# Stub functions
log() { :; }
warn() { :; }
error() { :; }
success() { :; }

# Source modules under test
source "${TEKHTON_HOME}/lib/causality.sh"
source "${TEKHTON_HOME}/lib/dashboard.sh"

# --- Test: init_dashboard creates directory structure ---
init_causal_log
init_dashboard "$PROJECT_DIR"

dash_dir="${PROJECT_DIR}/${DASHBOARD_DIR}"
[[ -d "${dash_dir}/data" ]] || { echo "FAIL: dashboard data dir not created"; exit 1; }
[[ -f "${dash_dir}/data/run_state.js" ]] || { echo "FAIL: run_state.js not created"; exit 1; }
[[ -f "${dash_dir}/data/timeline.js" ]] || { echo "FAIL: timeline.js not created"; exit 1; }
[[ -f "${dash_dir}/data/milestones.js" ]] || { echo "FAIL: milestones.js not created"; exit 1; }

# Validate JS format
head -1 "${dash_dir}/data/run_state.js" | grep -q "Generated by Tekhton" || \
    { echo "FAIL: run_state.js missing header"; exit 1; }
grep -q "window.TK_RUN_STATE" "${dash_dir}/data/run_state.js" || \
    { echo "FAIL: run_state.js missing TK_RUN_STATE"; exit 1; }

# --- Test: cleanup_dashboard removes directory ---
cleanup_dashboard "$PROJECT_DIR"
[[ ! -d "$dash_dir" ]] || { echo "FAIL: dashboard dir not removed after cleanup"; exit 1; }

# --- Test: config transition (disable → cleanup, enable → recreate) ---
DASHBOARD_ENABLED=true
init_dashboard "$PROJECT_DIR"
[[ -d "${dash_dir}/data" ]] || { echo "FAIL: dashboard not recreated"; exit 1; }

DASHBOARD_ENABLED=false
# is_dashboard_enabled should return 1 (false)
if is_dashboard_enabled; then
    echo "FAIL: is_dashboard_enabled returned true when disabled"
    exit 1
fi
DASHBOARD_ENABLED=true

# --- Test: emit_dashboard_run_state generates valid JS ---
declare -A _STAGE_STATUS=([intake]="complete" [coder]="running")
declare -A _STAGE_TURNS=([intake]=4 [coder]=12)
declare -A _STAGE_BUDGET=([intake]=10 [coder]=50)
declare -A _STAGE_DURATION=([intake]=10 [coder]=45)
PIPELINE_STATUS="running"
CURRENT_STAGE="coder"
START_AT_TS="2026-03-15T10:00:00Z"
WAITING_FOR=""
_CURRENT_MILESTONE=""

emit_dashboard_run_state
[[ -f "${dash_dir}/data/run_state.js" ]] || { echo "FAIL: run_state.js not updated"; exit 1; }
grep -q '"pipeline_status":"running"' "${dash_dir}/data/run_state.js" || \
    { echo "FAIL: run_state.js missing pipeline_status"; exit 1; }
grep -q "window.TK_RUN_STATE" "${dash_dir}/data/run_state.js" || \
    { echo "FAIL: run_state.js missing TK_RUN_STATE"; exit 1; }

# --- Test: emit_dashboard_milestones reads manifest ---
mkdir -p "${TMPDIR}/.claude/milestones"
MILESTONE_DIR="${TMPDIR}/.claude/milestones"
MILESTONE_MANIFEST="MANIFEST.cfg"
cat > "${MILESTONE_DIR}/MANIFEST.cfg" << 'EOF'
# id|title|status|depends_on|file|parallel_group
m01|DAG Infrastructure|done||m01-dag-infra.md|foundation
m02|Sliding Window|pending|m01|m02-sliding-window.md|foundation
m03|Test Milestone|in_progress|m02|m03-test.md|
EOF

emit_dashboard_milestones
grep -q "TK_MILESTONES" "${dash_dir}/data/milestones.js" || \
    { echo "FAIL: milestones.js missing TK_MILESTONES"; exit 1; }
grep -q "DAG Infrastructure" "${dash_dir}/data/milestones.js" || \
    { echo "FAIL: milestones.js missing milestone title"; exit 1; }
grep -q '"status":"done"' "${dash_dir}/data/milestones.js" || \
    { echo "FAIL: milestones.js missing status"; exit 1; }

# --- Test: _regenerate_timeline_js from causal log ---
: > "$CAUSAL_LOG_FILE"
_CAUSAL_EVENT_COUNT=0
rm -rf "$_CAUSAL_SEQ_DIR"/* 2>/dev/null || true
emit_event "pipeline_start" "pipeline" "test" "" "" "" > /dev/null
emit_event "stage_start" "coder" "" "pipeline.001" "" "" > /dev/null
emit_event "stage_end" "coder" "" "coder.001" "" "" > /dev/null

_regenerate_timeline_js
[[ -f "${dash_dir}/data/timeline.js" ]] || { echo "FAIL: timeline.js not generated"; exit 1; }
grep -q "TK_TIMELINE" "${dash_dir}/data/timeline.js" || \
    { echo "FAIL: timeline.js missing TK_TIMELINE"; exit 1; }
grep -q "pipeline_start" "${dash_dir}/data/timeline.js" || \
    { echo "FAIL: timeline.js missing events"; exit 1; }

# --- Test: timeline respects verbosity=minimal ---
DASHBOARD_VERBOSITY=minimal
_regenerate_timeline_js
# minimal should include stage_end but not stage_start
grep -q "stage_end" "${dash_dir}/data/timeline.js" || \
    { echo "FAIL: minimal timeline missing stage_end"; exit 1; }
DASHBOARD_VERBOSITY=normal

# --- Test: emit_dashboard_reports parses stage reports ---
cat > "${TMPDIR}/CODER_SUMMARY.md" << 'EOF'
## Status: COMPLETE
## What Was Implemented
- Added feature X
- Fixed bug Y
## Files Modified
- lib/foo.sh
- lib/bar.sh
EOF
cat > "${TMPDIR}/REVIEWER_REPORT.md" << 'EOF'
## Verdict
APPROVED
## Feedback
Good work.
EOF

cd "$TMPDIR"
emit_dashboard_reports
grep -q "TK_REPORTS" "${dash_dir}/data/reports.js" || \
    { echo "FAIL: reports.js missing TK_REPORTS"; exit 1; }
grep -q '"coder"' "${dash_dir}/data/reports.js" || \
    { echo "FAIL: reports.js missing coder section"; exit 1; }

# --- Test: emit_dashboard_security parses security report ---
SECURITY_REPORT_FILE="${TMPDIR}/SECURITY_REPORT.md"
cat > "$SECURITY_REPORT_FILE" << 'EOF'
## Security Findings
- HIGH: SQL injection in handler.py:42 (A03)
- LOW: Debug logging enabled
## Summary
2 findings.
EOF

emit_dashboard_security
grep -q "TK_SECURITY" "${dash_dir}/data/security.js" || \
    { echo "FAIL: security.js missing TK_SECURITY"; exit 1; }
grep -q '"HIGH"' "${dash_dir}/data/security.js" || \
    { echo "FAIL: security.js missing HIGH severity"; exit 1; }

# --- Test: emit_dashboard_metrics reads RUN_SUMMARY.json ---
cat > "${LOG_DIR}/RUN_SUMMARY.json" << 'EOF'
{
    "outcome": "success",
    "total_turns": 45,
    "total_time_s": 300,
    "milestone": "m03"
}
EOF

emit_dashboard_metrics
grep -q "TK_METRICS" "${dash_dir}/data/metrics.js" || \
    { echo "FAIL: metrics.js missing TK_METRICS"; exit 1; }
grep -q '"outcome"' "${dash_dir}/data/metrics.js" || \
    { echo "FAIL: metrics.js missing outcome data"; exit 1; }

# --- Test: dashboard disabled = no-op ---
DASHBOARD_ENABLED=false
# These should all be silent no-ops
emit_dashboard_run_state
emit_dashboard_milestones
emit_dashboard_security
emit_dashboard_reports
emit_dashboard_metrics
DASHBOARD_ENABLED=true

# --- Test: _json_escape handles edge cases ---
esc=$(_json_escape 'line1
line2	tab"quoted"\\back')
[[ "$esc" == 'line1\nline2\ttab\"quoted\"\\\\back' ]] || \
    { echo "FAIL: _json_escape produced: $esc"; exit 1; }

# --- Test: _parse_run_summaries with python fallback ---
result=$(_parse_run_summaries "$LOG_DIR" 5)
echo "$result" | grep -q "success" || \
    { echo "FAIL: _parse_run_summaries didn't find success outcome"; exit 1; }

# --- Test: emit_dashboard_run_state waiting_for null-patching -----------------
# When WAITING_FOR is empty, the printf format string produces:
#   "waiting_for":,"started_at":...
# The string replacement must fix this to "waiting_for":null,...
# This tests the empty-waiting branch of the null-patch logic.
WAITING_FOR=""
emit_dashboard_run_state
# Must contain waiting_for:null (not a bare comma or empty string)
grep -q '"waiting_for":null' "${dash_dir}/data/run_state.js" || \
    { echo "FAIL: waiting_for not null when WAITING_FOR is empty"; cat "${dash_dir}/data/run_state.js"; exit 1; }
# Must NOT contain the malformed "waiting_for":, pattern
grep -q '"waiting_for":,' "${dash_dir}/data/run_state.js" && \
    { echo "FAIL: waiting_for has bare comma (null-patch did not fire)"; exit 1; } || true

# When WAITING_FOR is set, must emit quoted string value
WAITING_FOR="human_action"
emit_dashboard_run_state
grep -q '"waiting_for":"human_action"' "${dash_dir}/data/run_state.js" || \
    { echo "FAIL: waiting_for not emitted as string when set"; exit 1; }
WAITING_FOR=""

echo "All dashboard data tests passed."
