#!/usr/bin/env bash
set -euo pipefail
# =============================================================================
# dashboard_parsers.sh — Report parsing functions for dashboard data emission
#
# Sourced by dashboard.sh — do not run directly.
# Expects: _json_escape() from causality.sh
# =============================================================================

# _to_js_timestamp
# Returns current ISO 8601 timestamp for generated file headers.
_to_js_timestamp() {
    date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date +"%Y-%m-%dT%H:%M:%SZ"
}

# _to_js_string VARNAME JSON_CONTENT
# Wraps JSON content in a JS global assignment with header comment.
_to_js_string() {
    local varname="$1"
    local json_content="$2"
    local ts
    ts=$(_to_js_timestamp)
    printf '// Generated by Tekhton Watchtower — do not edit\n'
    printf '// Updated: %s\n' "$ts"
    printf 'window.%s = %s;\n' "$varname" "$json_content"
}

# _write_js_file FILEPATH VARNAME JSON_CONTENT
# Atomically writes a JS data file (tmpfile + mv).
_write_js_file() {
    local filepath="$1"
    local varname="$2"
    local json_content="$3"

    local tmpfile="${filepath}.tmp.$$"
    _to_js_string "$varname" "$json_content" > "$tmpfile"
    mv "$tmpfile" "$filepath"
}

# _parse_security_report FILE
# Extract findings from SECURITY_REPORT.md into JSON array.
_parse_security_report() {
    local file="$1"
    [[ ! -f "$file" ]] && { echo "[]"; return 0; }

    local findings="["
    local first=true
    local in_findings=false

    while IFS= read -r line; do
        # Detect findings section
        if [[ "$line" =~ ^##.*[Ff]indings ]]; then
            in_findings=true
            continue
        fi
        if [[ "$in_findings" = true ]] && [[ "$line" =~ ^## ]] && [[ ! "$line" =~ [Ff]indings ]]; then
            in_findings=false
            continue
        fi

        if [[ "$in_findings" = true ]] && [[ "$line" =~ ^[-*][[:space:]] ]]; then
            local severity="INFO"
            local category=""
            local detail
            detail="$(_json_escape "$line")"

            if echo "$line" | grep -qi "CRITICAL" 2>/dev/null; then severity="CRITICAL"
            elif echo "$line" | grep -qi "HIGH" 2>/dev/null; then severity="HIGH"
            elif echo "$line" | grep -qi "MEDIUM" 2>/dev/null; then severity="MEDIUM"
            elif echo "$line" | grep -qi "LOW" 2>/dev/null; then severity="LOW"
            fi

            # Try to extract OWASP category
            category=$(echo "$line" | grep -oP 'A\d{2}' 2>/dev/null | head -1 || true)

            if [[ "$first" = true ]]; then
                first=false
            else
                findings="${findings},"
            fi
            findings="${findings}{\"severity\":\"${severity}\",\"category\":\"$(_json_escape "$category")\",\"detail\":\"${detail}\"}"
        fi
    done < "$file"

    findings="${findings}]"
    echo "$findings"
}

# _parse_intake_report FILE
# Extract verdict and confidence from INTAKE_REPORT.md.
# Handles two formats:
#   Format A (inline): "Verdict: PASS"  /  "Confidence: 82"
#   Format B (header):  "## Verdict\nPASS"  /  "## Confidence\n82"
_parse_intake_report() {
    local file="$1"
    [[ ! -f "$file" ]] && { echo "null"; return 0; }

    local verdict=""
    local confidence=""

    # Try inline format first (portable sed, no grep -P)
    verdict=$(sed -n 's/^[#]* *[Vv]erdict[: ]*//p' "$file" 2>/dev/null | head -1 | tr -d '[:space:]')
    # If inline failed, try header-then-next-line format
    if [[ -z "$verdict" ]]; then
        verdict=$(awk '/^##? *[Vv]erdict/{getline; gsub(/^[[:space:]]+|[[:space:]]+$/,""); print; exit}' "$file" 2>/dev/null)
    fi

    confidence=$(sed -n 's/^[#]* *[Cc]onfidence[: ]*//p' "$file" 2>/dev/null | head -1 | grep -oE '[0-9]+' | head -1)
    if [[ -z "$confidence" ]]; then
        confidence=$(awk '/^##? *[Cc]onfidence/{getline; gsub(/[^0-9]/,""); print; exit}' "$file" 2>/dev/null)
    fi

    # Extract task text from "Tweaked Content" section (falls back to empty)
    local task_text=""
    task_text=$(awk '/^## Tweaked Content/{found=1; next} found && /^## /{exit} found && /^###/{exit} found{print}' "$file" 2>/dev/null | sed '/^$/d' | head -5 || true)
    # Strip leading/trailing whitespace; collapse newlines to single space
    task_text=$(printf '%s' "$task_text" | tr '\n' ' ' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//;s/  */ /g')

    printf '{"verdict":"%s","confidence":%s,"task_text":"%s"}' \
        "$(_json_escape "${verdict:-unknown}")" \
        "${confidence:-0}" \
        "$(_json_escape "${task_text}")"
}

# _parse_coder_summary FILE
# Extract status and file list from CODER_SUMMARY.md.
# Handles: "## Status: COMPLETE", "## Status\nCOMPLETE", "Status: IN PROGRESS"
_parse_coder_summary() {
    local file="$1"
    [[ ! -f "$file" ]] && { echo "null"; return 0; }

    local status=""
    # Try inline "## Status: VALUE" (most common format)
    status=$(sed -n 's/^[#]* *Status[: ]*//p' "$file" 2>/dev/null | head -1 | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
    # Fallback: header then next line
    if [[ -z "$status" ]]; then
        status=$(awk '/^##? *Status *$/{getline; gsub(/^[[:space:]]+|[[:space:]]+$/,""); print; exit}' "$file" 2>/dev/null)
    fi

    local file_count=0
    file_count=$(awk '/^## Files ([Cc]reated|[Mm]odified)/{f=1;next} f && /^##/{exit} f && /^[-*]/{c++} END{print c+0}' \
        "$file" 2>/dev/null || echo "0")

    printf '{"status":"%s","files_modified":%s}' \
        "$(_json_escape "${status:-unknown}")" \
        "$file_count"
}

# _parse_reviewer_report FILE
# Extract verdict from REVIEWER_REPORT.md.
_parse_reviewer_report() {
    local file="$1"
    [[ ! -f "$file" ]] && { echo "null"; return 0; }

    local verdict=""
    verdict=$(grep -m1 "^## Verdict" -A1 "$file" 2>/dev/null | tail -1 | tr -d '[:space:]' || true)

    printf '{"verdict":"%s"}' "$(_json_escape "${verdict:-unknown}")"
}

# _parse_run_summaries DIR DEPTH
# Read last N run records from metrics.jsonl (primary) or RUN_SUMMARY_*.json
# files (fallback). metrics.jsonl is authoritative because it accumulates
# across all runs and is written by _hook_record_metrics before dashboard
# emission. Individual RUN_SUMMARY_*.json files are only a fallback for
# projects that have them but lack a metrics.jsonl.
_parse_run_summaries() {
    local dir="$1"
    local depth="${2:-50}"

    local metrics_file="${dir}/metrics.jsonl"

    # Primary path: read from metrics.jsonl (has all historical data)
    if [[ -f "$metrics_file" ]] && [[ -s "$metrics_file" ]]; then
        _parse_run_summaries_from_jsonl "$metrics_file" "$depth"
        return
    fi

    # Fallback: read individual RUN_SUMMARY_*.json files
    _parse_run_summaries_from_files "$dir" "$depth"
}

# _parse_run_summaries_from_jsonl METRICS_FILE DEPTH
# Parse metrics.jsonl (one JSON object per line) and convert to the runs
# array format expected by the frontend. Reads the last DEPTH lines.
_parse_run_summaries_from_jsonl() {
    local metrics_file="$1"
    local depth="$2"

    # Prefer python3 for reliable JSON parsing
    if command -v python3 &>/dev/null; then
        local py_result
        py_result=$(python3 -c "
import json, sys
results = []
lines = []
with open(sys.argv[1]) as f:
    for line in f:
        line = line.strip()
        if line:
            lines.append(line)
# Take last N lines (most recent runs)
for line in lines[-int(sys.argv[2]):]:
    try:
        d = json.loads(line)
        # Derive run_type from task_type + milestone_mode
        run_type = 'adhoc'
        if d.get('milestone_mode') is True or d.get('milestone_mode') == 'true':
            run_type = 'milestone'
        else:
            tt = d.get('task_type', '')
            if tt == 'bug':
                run_type = 'human_bug'
            elif tt == 'feature':
                run_type = 'human_feat'
            elif tt == 'polish':
                run_type = 'human_polish'
            elif tt == 'drift':
                run_type = 'drift'
        # Build per-stage data from individual turn counts
        stages = {}
        for sname, skey in [('coder','coder_turns'),('reviewer','reviewer_turns'),('tester','tester_turns'),('scout','scout_turns')]:
            t = d.get(skey, 0)
            if t and int(t) > 0:
                stages[sname] = {'turns': int(t), 'duration_s': 0, 'budget': 0}
        # Task label: first 80 chars of task
        task = d.get('task', '')
        task_label = task[:80] if task else ''
        results.append({
            'outcome': d.get('outcome', 'unknown'),
            'total_turns': d.get('total_turns', 0),
            'total_time_s': d.get('total_time_s', 0),
            'milestone': '',
            'run_type': run_type,
            'task_label': task_label,
            'timestamp': d.get('timestamp', ''),
            'team': '',
            'stages': stages
        })
    except:
        pass
# Reverse so newest is first
results.reverse()
print(json.dumps(results))
" "$metrics_file" "$depth" 2>/dev/null || true)

        if [[ -n "$py_result" ]] && [[ "$py_result" != "[]" ]]; then
            echo "$py_result"
            return
        fi
    fi

    # Fallback: portable sed/awk extraction from JSONL
    local result="["
    local first=true
    local count=0

    while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        [[ "$count" -ge "$depth" ]] && break

        local outcome
        outcome=$(printf '%s' "$line" | sed -n 's/.*"outcome"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
        : "${outcome:=unknown}"
        local turns
        turns=$(printf '%s' "$line" | sed -n 's/.*"total_turns"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p' | head -1)
        : "${turns:=0}"
        local time_s
        time_s=$(printf '%s' "$line" | sed -n 's/.*"total_time_s"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p' | head -1)
        : "${time_s:=0}"
        local task_type
        task_type=$(printf '%s' "$line" | sed -n 's/.*"task_type"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
        : "${task_type:=adhoc}"
        local ms_mode
        ms_mode=$(printf '%s' "$line" | sed -n 's/.*"milestone_mode"[[:space:]]*:[[:space:]]*\([a-z]*\).*/\1/p' | head -1)
        local run_type="adhoc"
        if [[ "$ms_mode" = "true" ]]; then
            run_type="milestone"
        else
            case "$task_type" in
                bug) run_type="human_bug" ;;
                feature) run_type="human_feat" ;;
                polish) run_type="human_polish" ;;
                drift) run_type="drift" ;;
            esac
        fi
        local task_label
        task_label=$(printf '%s' "$line" | sed -n 's/.*"task"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
        task_label="${task_label:0:80}"
        local timestamp
        timestamp=$(printf '%s' "$line" | sed -n 's/.*"timestamp"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)

        local json_content
        json_content="{\"outcome\":\"${outcome}\",\"total_turns\":${turns},\"total_time_s\":${time_s},\"milestone\":\"\",\"run_type\":\"${run_type}\",\"task_label\":\"${task_label}\",\"timestamp\":\"${timestamp}\",\"stages\":{}}"

        if [[ "$first" = true ]]; then
            first=false
        else
            result="${result},"
        fi
        result="${result}${json_content}"
        count=$(( count + 1 ))
    done < <(tail -n "$depth" "$metrics_file" 2>/dev/null | tac 2>/dev/null || tail -n "$depth" "$metrics_file")

    result="${result}]"
    echo "$result"
}

# _parse_run_summaries_from_files DIR DEPTH
# Legacy path: read individual RUN_SUMMARY_*.json files (fallback when
# metrics.jsonl doesn't exist).
_parse_run_summaries_from_files() {
    local dir="$1"
    local depth="${2:-50}"

    local result="["
    local first=true
    local count=0

    while IFS= read -r summary_file; do
        [[ "$count" -ge "$depth" ]] && break
        [[ ! -f "$summary_file" ]] && continue

        local json_content=""
        # Prefer python3 for JSON parsing if available
        if command -v python3 &>/dev/null; then
            json_content=$(python3 -c "
import json, sys
try:
    with open(sys.argv[1]) as f:
        d = json.load(f)
    print(json.dumps({
        'outcome': d.get('outcome', 'unknown'),
        'total_turns': d.get('total_turns', d.get('total_agent_calls', 0)),
        'total_time_s': d.get('total_time_s', d.get('wall_clock_seconds', 0)),
        'milestone': d.get('milestone', ''),
        'run_type': d.get('run_type', 'adhoc'),
        'task_label': d.get('task_label', ''),
        'timestamp': d.get('timestamp', ''),
        'team': d.get('team', ''),
        'stages': d.get('stages', {})
    }))
except: pass
" "$summary_file" 2>/dev/null || true)
        fi

        # Fallback: portable sed extraction (no grep -P)
        if [[ -z "$json_content" ]]; then
            local outcome
            outcome=$(sed -n 's/.*"outcome"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$summary_file" 2>/dev/null | head -1)
            : "${outcome:=unknown}"
            local turns
            turns=$(sed -n 's/.*"total_turns"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p' "$summary_file" 2>/dev/null | head -1)
            [[ -z "$turns" ]] && turns=$(sed -n 's/.*"total_agent_calls"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p' "$summary_file" 2>/dev/null | head -1)
            : "${turns:=0}"
            local time_s
            time_s=$(sed -n 's/.*"total_time_s"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p' "$summary_file" 2>/dev/null | head -1)
            [[ -z "$time_s" ]] && time_s=$(sed -n 's/.*"wall_clock_seconds"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p' "$summary_file" 2>/dev/null | head -1)
            : "${time_s:=0}"
            local milestone
            milestone=$(sed -n 's/.*"milestone"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$summary_file" 2>/dev/null | head -1)
            : "${milestone:=}"
            local run_type
            run_type=$(sed -n 's/.*"run_type"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$summary_file" 2>/dev/null | head -1)
            : "${run_type:=adhoc}"
            local task_label
            task_label=$(sed -n 's/.*"task_label"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$summary_file" 2>/dev/null | head -1)
            : "${task_label:=}"
            json_content="{\"outcome\":\"${outcome}\",\"total_turns\":${turns},\"total_time_s\":${time_s},\"milestone\":\"${milestone}\",\"run_type\":\"${run_type}\",\"task_label\":\"${task_label}\",\"stages\":{}}"
        fi

        if [[ -n "$json_content" ]]; then
            if [[ "$first" = true ]]; then
                first=false
            else
                result="${result},"
            fi
            result="${result}${json_content}"
        fi
        count=$(( count + 1 ))
    done < <(ls -t "$dir"/RUN_SUMMARY_*.json 2>/dev/null || true)

    result="${result}]"
    echo "$result"
}
