#!/usr/bin/env bash
set -euo pipefail
# =============================================================================
# dashboard_parsers.sh — Report parsing functions for dashboard data emission
#
# Sourced by dashboard.sh — do not run directly.
# Expects: _json_escape() from causality.sh
# =============================================================================

# _to_js_timestamp
# Returns current ISO 8601 timestamp for generated file headers.
_to_js_timestamp() {
    date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date +"%Y-%m-%dT%H:%M:%SZ"
}

# _to_js_string VARNAME JSON_CONTENT
# Wraps JSON content in a JS global assignment with header comment.
_to_js_string() {
    local varname="$1"
    local json_content="$2"
    local ts
    ts=$(_to_js_timestamp)
    printf '// Generated by Tekhton Watchtower — do not edit\n'
    printf '// Updated: %s\n' "$ts"
    printf 'window.%s = %s;\n' "$varname" "$json_content"
}

# _write_js_file FILEPATH VARNAME JSON_CONTENT
# Atomically writes a JS data file (tmpfile + mv).
_write_js_file() {
    local filepath="$1"
    local varname="$2"
    local json_content="$3"

    local tmpfile="${filepath}.tmp.$$"
    _to_js_string "$varname" "$json_content" > "$tmpfile"
    mv "$tmpfile" "$filepath"
}

# _parse_security_report FILE
# Extract findings from SECURITY_REPORT.md into JSON array.
_parse_security_report() {
    local file="$1"
    [[ ! -f "$file" ]] && { echo "[]"; return 0; }

    local findings="["
    local first=true
    local in_findings=false

    while IFS= read -r line; do
        # Detect findings section
        if [[ "$line" =~ ^##.*[Ff]indings ]]; then
            in_findings=true
            continue
        fi
        if [[ "$in_findings" = true ]] && [[ "$line" =~ ^## ]] && [[ ! "$line" =~ [Ff]indings ]]; then
            in_findings=false
            continue
        fi

        if [[ "$in_findings" = true ]] && [[ "$line" =~ ^[-*][[:space:]] ]]; then
            local severity="INFO"
            local category=""
            local detail
            detail="$(_json_escape "$line")"

            if echo "$line" | grep -qi "CRITICAL" 2>/dev/null; then severity="CRITICAL"
            elif echo "$line" | grep -qi "HIGH" 2>/dev/null; then severity="HIGH"
            elif echo "$line" | grep -qi "MEDIUM" 2>/dev/null; then severity="MEDIUM"
            elif echo "$line" | grep -qi "LOW" 2>/dev/null; then severity="LOW"
            fi

            # Try to extract OWASP category
            category=$(echo "$line" | grep -oP 'A\d{2}' 2>/dev/null | head -1 || true)

            if [[ "$first" = true ]]; then
                first=false
            else
                findings="${findings},"
            fi
            findings="${findings}{\"severity\":\"${severity}\",\"category\":\"$(_json_escape "$category")\",\"detail\":\"${detail}\"}"
        fi
    done < "$file"

    findings="${findings}]"
    echo "$findings"
}

# _parse_intake_report FILE
# Extract verdict and confidence from INTAKE_REPORT.md.
_parse_intake_report() {
    local file="$1"
    [[ ! -f "$file" ]] && { echo "null"; return 0; }

    local verdict=""
    local confidence=""

    verdict=$(grep -m1 -oP '(?<=Verdict:\s).*' "$file" 2>/dev/null || \
              grep -m1 -oP '(?<=verdict:\s).*' "$file" 2>/dev/null || true)
    confidence=$(grep -m1 -oP '(?<=[Cc]onfidence:\s)\d+' "$file" 2>/dev/null || true)

    printf '{"verdict":"%s","confidence":%s}' \
        "$(_json_escape "${verdict:-unknown}")" \
        "${confidence:-0}"
}

# _parse_coder_summary FILE
# Extract status and file list from CODER_SUMMARY.md.
_parse_coder_summary() {
    local file="$1"
    [[ ! -f "$file" ]] && { echo "null"; return 0; }

    local status=""
    status=$(grep -m1 -oP '(?<=Status:\s).*' "$file" 2>/dev/null || true)

    local file_count=0
    file_count=$(awk '/^## Files ([Cc]reated|[Mm]odified)/{f=1;next} f && /^##/{exit} f && /^[-*]/{c++} END{print c+0}' \
        "$file" 2>/dev/null || echo "0")

    printf '{"status":"%s","files_modified":%s}' \
        "$(_json_escape "${status:-unknown}")" \
        "$file_count"
}

# _parse_reviewer_report FILE
# Extract verdict from REVIEWER_REPORT.md.
_parse_reviewer_report() {
    local file="$1"
    [[ ! -f "$file" ]] && { echo "null"; return 0; }

    local verdict=""
    verdict=$(grep -m1 "^## Verdict" -A1 "$file" 2>/dev/null | tail -1 | tr -d '[:space:]' || true)

    printf '{"verdict":"%s"}' "$(_json_escape "${verdict:-unknown}")"
}

# _parse_run_summaries DIR DEPTH
# Read last N RUN_SUMMARY.json files, extract per-run metrics.
_parse_run_summaries() {
    local dir="$1"
    local depth="${2:-50}"

    local result="["
    local first=true
    local count=0

    while IFS= read -r summary_file; do
        [[ "$count" -ge "$depth" ]] && break
        [[ ! -f "$summary_file" ]] && continue

        local json_content=""
        # Prefer python3 for JSON parsing if available
        if command -v python3 &>/dev/null; then
            json_content=$(python3 -c "
import json, sys
try:
    with open(sys.argv[1]) as f:
        d = json.load(f)
    print(json.dumps({
        'outcome': d.get('outcome', 'unknown'),
        'total_turns': d.get('total_turns', 0),
        'total_time_s': d.get('total_time_s', 0),
        'milestone': d.get('milestone', ''),
        'stages': d.get('stages', {})
    }))
except: pass
" "$summary_file" 2>/dev/null || true)
        fi

        # Fallback: grep/awk extraction
        if [[ -z "$json_content" ]]; then
            local outcome
            outcome=$(grep -oP '"outcome"\s*:\s*"\K[^"]+' "$summary_file" 2>/dev/null || echo "unknown")
            local turns
            turns=$(grep -oP '"total_turns"\s*:\s*\K[0-9]+' "$summary_file" 2>/dev/null || echo "0")
            local time_s
            time_s=$(grep -oP '"total_time_s"\s*:\s*\K[0-9]+' "$summary_file" 2>/dev/null || echo "0")
            json_content="{\"outcome\":\"${outcome}\",\"total_turns\":${turns},\"total_time_s\":${time_s}}"
        fi

        if [[ -n "$json_content" ]]; then
            if [[ "$first" = true ]]; then
                first=false
            else
                result="${result},"
            fi
            result="${result}${json_content}"
        fi
        count=$(( count + 1 ))
    done < <(ls -t "$dir"/RUN_SUMMARY*.json 2>/dev/null || true)

    result="${result}]"
    echo "$result"
}
