#!/usr/bin/env bash
set -euo pipefail
# =============================================================================
# dashboard_emitters.sh — Dashboard data emitter functions
#
# Sourced by tekhton.sh — do not run directly.
# Expects: causality.sh, dashboard_parsers.sh, and dashboard.sh sourced first.
# Expects: PROJECT_DIR, TEKHTON_HOME (set by caller/config)
#
# Provides:
#   _regenerate_timeline_js    — rebuild data/timeline.js from causal log
#   emit_dashboard_milestones  — generate data/milestones.js
#   emit_dashboard_security    — generate data/security.js
#   emit_dashboard_reports     — generate data/reports.js
#   emit_dashboard_metrics     — generate data/metrics.js
#   emit_dashboard_health      — generate data/health.js
# =============================================================================

# --- Timeline emission --------------------------------------------------------

# _regenerate_timeline_js
# Rebuild data/timeline.js from the causal log.
# Respects DASHBOARD_MAX_TIMELINE_EVENTS cap.
_regenerate_timeline_js() {
    if ! is_dashboard_enabled; then return 0; fi

    local dash_dir="${PROJECT_DIR:-.}/${DASHBOARD_DIR:-.claude/dashboard}"
    [[ ! -d "${dash_dir}/data" ]] && return 0
    [[ ! -f "${CAUSAL_LOG_FILE:-}" ]] && return 0

    : "${DASHBOARD_MAX_TIMELINE_EVENTS:=500}"
    : "${DASHBOARD_VERBOSITY:=normal}"

    local tmpfile="${dash_dir}/data/timeline.js.tmp.$$"
    {
        printf '// Generated by Tekhton Watchtower — do not edit\n'
        printf '// Updated: %s\n' "$(_to_js_timestamp)"
        printf 'window.TK_TIMELINE = [\n'

        local count=0
        local first=true
        # Apply verbosity filter
        local filter_pattern=""
        case "$DASHBOARD_VERBOSITY" in
            minimal) filter_pattern='"type":"stage_end"\|"type":"verdict"' ;;
            normal)  filter_pattern='"type":"stage_\|"type":"verdict"\|"type":"finding"\|"type":"build_gate"\|"type":"pipeline_\|"type":"milestone_"' ;;
            verbose) filter_pattern="" ;;  # no filter — include everything
        esac

        # Read from causal log, apply filter, cap at max events
        # Use tail to get most recent events if log exceeds cap
        local lines
        if [[ -n "$filter_pattern" ]]; then
            lines=$(grep "$filter_pattern" "$CAUSAL_LOG_FILE" 2>/dev/null | tail -n "$DASHBOARD_MAX_TIMELINE_EVENTS" || true)
        else
            lines=$(tail -n "$DASHBOARD_MAX_TIMELINE_EVENTS" "$CAUSAL_LOG_FILE" 2>/dev/null || true)
        fi

        while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            if [[ "$first" = true ]]; then
                first=false
            else
                printf ',\n'
            fi
            printf '  %s' "$line"
            count=$(( count + 1 ))
        done <<< "$lines"

        printf '\n];\n'
    } > "$tmpfile"
    mv "$tmpfile" "${dash_dir}/data/timeline.js"
}

# --- Milestone emission -------------------------------------------------------

# emit_dashboard_milestones
# Reads MANIFEST.cfg and generates data/milestones.js.
emit_dashboard_milestones() {
    if ! is_dashboard_enabled; then return 0; fi

    local dash_dir="${PROJECT_DIR:-.}/${DASHBOARD_DIR:-.claude/dashboard}"
    [[ ! -d "${dash_dir}/data" ]] && return 0

    local manifest="${MILESTONE_DIR:-${PROJECT_DIR:-.}/.claude/milestones}/${MILESTONE_MANIFEST:-MANIFEST.cfg}"

    local json="["
    local first=true

    if [[ -f "$manifest" ]]; then
        while IFS='|' read -r mid title status deps _mfile pgroup; do
            # Skip comments and empty lines
            [[ -z "$mid" ]] && continue
            [[ "$mid" =~ ^[[:space:]]*# ]] && continue
            mid="${mid## }"; mid="${mid%% }"
            title="${title## }"; title="${title%% }"
            status="${status## }"; status="${status%% }"
            deps="${deps## }"; deps="${deps%% }"
            pgroup="${pgroup## }"; pgroup="${pgroup%% }"

            if [[ "$first" = true ]]; then first=false; else json="${json},"; fi
            json="${json}{\"id\":\"$(_json_escape "$mid")\",\"title\":\"$(_json_escape "$title")\",\"status\":\"$(_json_escape "$status")\",\"depends_on\":\"$(_json_escape "$deps")\",\"parallel_group\":\"$(_json_escape "$pgroup")\"}"
        done < "$manifest"
    fi

    json="${json}]"
    _write_js_file "${dash_dir}/data/milestones.js" "TK_MILESTONES" "$json"
}

# --- Security emission --------------------------------------------------------

# emit_dashboard_security
# Parses SECURITY_REPORT.md and generates data/security.js.
emit_dashboard_security() {
    if ! is_dashboard_enabled; then return 0; fi

    local dash_dir="${PROJECT_DIR:-.}/${DASHBOARD_DIR:-.claude/dashboard}"
    [[ ! -d "${dash_dir}/data" ]] && return 0

    local findings
    findings=$(_parse_security_report "${SECURITY_REPORT_FILE:-SECURITY_REPORT.md}")

    local json="{\"findings\":${findings}}"
    _write_js_file "${dash_dir}/data/security.js" "TK_SECURITY" "$json"
}

# --- Reports emission ---------------------------------------------------------

# emit_dashboard_reports
# Parses stage reports and generates data/reports.js.
emit_dashboard_reports() {
    if ! is_dashboard_enabled; then return 0; fi

    local dash_dir="${PROJECT_DIR:-.}/${DASHBOARD_DIR:-.claude/dashboard}"
    [[ ! -d "${dash_dir}/data" ]] && return 0

    local intake
    intake=$(_parse_intake_report "${INTAKE_REPORT_FILE:-INTAKE_REPORT.md}")
    local coder
    coder=$(_parse_coder_summary "CODER_SUMMARY.md")
    local reviewer
    reviewer=$(_parse_reviewer_report "REVIEWER_REPORT.md")

    # Test audit verdict (M20)
    local audit_verdict="skipped"
    local audit_file="${TEST_AUDIT_REPORT_FILE:-TEST_AUDIT_REPORT.md}"
    if [[ -f "$audit_file" ]]; then
        audit_verdict=$(grep -oiE 'Verdict:\s*(NEEDS_WORK|PASS|CONCERNS)' "$audit_file" 2>/dev/null \
            | head -1 | sed 's/.*:\s*//' | tr '[:lower:]' '[:upper:]' || echo "skipped")
        : "${audit_verdict:=skipped}"
    fi
    local high_findings=0
    local medium_findings=0
    if [[ -f "$audit_file" ]]; then
        high_findings=$(grep -c 'Severity: HIGH' "$audit_file" 2>/dev/null || echo "0")
        medium_findings=$(grep -c 'Severity: MEDIUM' "$audit_file" 2>/dev/null || echo "0")
    fi
    local test_audit
    test_audit="{\"verdict\":\"${audit_verdict}\",\"high_findings\":${high_findings},\"medium_findings\":${medium_findings}}"

    local json
    json="{\"intake\":${intake},\"coder\":${coder},\"reviewer\":${reviewer},\"test_audit\":${test_audit}}"
    _write_js_file "${dash_dir}/data/reports.js" "TK_REPORTS" "$json"
}

# --- Metrics emission ---------------------------------------------------------

# emit_dashboard_metrics
# Reads RUN_SUMMARY.json files and generates data/metrics.js.
emit_dashboard_metrics() {
    if ! is_dashboard_enabled; then return 0; fi

    local dash_dir="${PROJECT_DIR:-.}/${DASHBOARD_DIR:-.claude/dashboard}"
    [[ ! -d "${dash_dir}/data" ]] && return 0

    local summary_dir="${LOG_DIR:-${PROJECT_DIR:-.}/.claude/logs}"
    local depth="${DASHBOARD_HISTORY_DEPTH:-50}"

    local runs
    runs=$(_parse_run_summaries "$summary_dir" "$depth")

    local json="{\"runs\":${runs}}"
    _write_js_file "${dash_dir}/data/metrics.js" "TK_METRICS" "$json"
}

# --- Health emission ----------------------------------------------------------

# emit_dashboard_health
# Reads HEALTH_BASELINE.json and generates data/health.js.
emit_dashboard_health() {
    if ! is_dashboard_enabled; then return 0; fi

    local dash_dir="${PROJECT_DIR:-.}/${DASHBOARD_DIR:-.claude/dashboard}"
    [[ ! -d "${dash_dir}/data" ]] && return 0

    local baseline_file="${PROJECT_DIR:-.}/${HEALTH_BASELINE_FILE:-.claude/HEALTH_BASELINE.json}"

    if [[ ! -f "$baseline_file" ]]; then
        _write_js_file "${dash_dir}/data/health.js" "TK_HEALTH" '{"available":false}'
        return 0
    fi

    # Read the JSON baseline directly — it's already valid JSON
    local baseline_content
    baseline_content=$(cat "$baseline_file" 2>/dev/null || echo "{}")

    # Wrap with metadata
    local belt=""
    if command -v get_health_belt &>/dev/null; then
        local composite
        composite=$(_read_json_int "$baseline_file" "composite")
        belt=$(get_health_belt "$composite")
    fi

    local json
    json="{\"available\":true,\"belt\":\"$(_json_escape "$belt")\",\"data\":${baseline_content}}"
    _write_js_file "${dash_dir}/data/health.js" "TK_HEALTH" "$json"
}

# --- Init data emission (Milestone 22) ----------------------------------------

# emit_dashboard_init — Generates init data for Watchtower from INIT_REPORT.md.
# Args: $1 = project_dir (optional, defaults to PROJECT_DIR)
emit_dashboard_init() {
    if ! is_dashboard_enabled; then return 0; fi

    local project_dir="${1:-${PROJECT_DIR:-.}}"
    local dash_dir="${project_dir}/${DASHBOARD_DIR:-.claude/dashboard}"
    [[ ! -d "${dash_dir}/data" ]] && return 0

    local report_file="${project_dir}/INIT_REPORT.md"
    [[ ! -f "$report_file" ]] && return 0

    # Extract metadata from INIT_REPORT.md HTML comment
    local timestamp="" project_name="" file_count="" project_type=""
    local in_meta=false
    while IFS= read -r line; do
        if [[ "$line" == "<!-- init-report-meta" ]]; then
            in_meta=true; continue
        fi
        if [[ "$line" == "-->" ]]; then
            in_meta=false; continue
        fi
        if [[ "$in_meta" == "true" ]]; then
            case "$line" in
                timestamp:*)  timestamp="${line#timestamp: }" ;;
                project:*)    project_name="${line#project: }" ;;
                file_count:*) file_count="${line#file_count: }" ;;
                project_type:*) project_type="${line#project_type: }" ;;
            esac
        fi
    done < "$report_file"

    local json
    json="{\"available\":true,\"timestamp\":\"$(_json_escape "$timestamp")\","
    json+="\"project\":\"$(_json_escape "$project_name")\","
    json+="\"fileCount\":\"$(_json_escape "$file_count")\","
    json+="\"projectType\":\"$(_json_escape "$project_type")\"}"

    _write_js_file "${dash_dir}/data/init.js" "TK_INIT" "$json"
}
