#!/usr/bin/env bash
set -euo pipefail
# =============================================================================
# dashboard_parsers.sh — Report parsing functions for individual stage reports
# (security, intake, coder, reviewer). JS file emission utilities.
#
# Sourced by dashboard.sh — do not run directly.
# Expects: _json_escape() from causality.sh
# =============================================================================

# _to_js_timestamp
# Returns current ISO 8601 timestamp for generated file headers.
_to_js_timestamp() {
    date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date +"%Y-%m-%dT%H:%M:%SZ"
}

# _to_js_string VARNAME JSON_CONTENT
# Wraps JSON content in a JS global assignment with header comment.
_to_js_string() {
    local varname="$1"
    local json_content="$2"
    local ts
    ts=$(_to_js_timestamp)
    printf '// Generated by Tekhton Watchtower — do not edit\n'
    printf '// Updated: %s\n' "$ts"
    printf 'window.%s = %s;\n' "$varname" "$json_content"
}

# _write_js_file FILEPATH VARNAME JSON_CONTENT
# Atomically writes a JS data file (tmpfile + mv).
_write_js_file() {
    local filepath="$1"
    local varname="$2"
    local json_content="$3"

    local tmpfile
    tmpfile=$(mktemp "${filepath}.tmp.XXXXXX")
    _to_js_string "$varname" "$json_content" > "$tmpfile"
    mv "$tmpfile" "$filepath"
}

# _parse_security_report FILE
# Extract findings from ${SECURITY_REPORT_FILE} into JSON array.
_parse_security_report() {
    local file="$1"
    [[ ! -f "$file" ]] && { echo "[]"; return 0; }

    local findings="["
    local first=true
    local in_findings=false

    while IFS= read -r line; do
        # Detect findings section
        if [[ "$line" =~ ^##.*[Ff]indings ]]; then
            in_findings=true
            continue
        fi
        if [[ "$in_findings" = true ]] && [[ "$line" =~ ^## ]] && [[ ! "$line" =~ [Ff]indings ]]; then
            in_findings=false
            continue
        fi

        if [[ "$in_findings" = true ]] && [[ "$line" =~ ^[-*][[:space:]] ]]; then
            local severity="INFO"
            local category=""
            local detail
            detail="$(_json_escape "$line")"

            if echo "$line" | grep -qi "CRITICAL" 2>/dev/null; then severity="CRITICAL"
            elif echo "$line" | grep -qi "HIGH" 2>/dev/null; then severity="HIGH"
            elif echo "$line" | grep -qi "MEDIUM" 2>/dev/null; then severity="MEDIUM"
            elif echo "$line" | grep -qi "LOW" 2>/dev/null; then severity="LOW"
            fi

            # Try to extract OWASP category
            category=$(echo "$line" | grep -oP 'A\d{2}' 2>/dev/null | head -1 || true)

            if [[ "$first" = true ]]; then
                first=false
            else
                findings="${findings},"
            fi
            findings="${findings}{\"severity\":\"${severity}\",\"category\":\"$(_json_escape "$category")\",\"detail\":\"${detail}\"}"
        fi
    done < "$file"

    findings="${findings}]"
    echo "$findings"
}

# _parse_intake_report FILE
# Extract verdict and confidence from ${INTAKE_REPORT_FILE}.
# Handles two formats:
#   Format A (inline): "Verdict: PASS"  /  "Confidence: 82"
#   Format B (header):  "## Verdict\nPASS"  /  "## Confidence\n82"
_parse_intake_report() {
    local file="$1"
    [[ ! -f "$file" ]] && { echo "null"; return 0; }

    local verdict=""
    local confidence=""

    # Try inline format first (portable sed, no grep -P)
    verdict=$(sed -n 's/^[#]* *[Vv]erdict[: ]*//p' "$file" 2>/dev/null | head -1 | tr -d '[:space:]')
    # If inline failed, try header-then-next-line format
    if [[ -z "$verdict" ]]; then
        verdict=$(awk '/^##? *[Vv]erdict/{getline; gsub(/^[[:space:]]+|[[:space:]]+$/,""); print; exit}' "$file" 2>/dev/null)
    fi

    confidence=$(sed -n 's/^[#]* *[Cc]onfidence[: ]*//p' "$file" 2>/dev/null | head -1 | grep -oE '[0-9]+' | head -1)
    if [[ -z "$confidence" ]]; then
        confidence=$(awk '/^##? *[Cc]onfidence/{getline; gsub(/[^0-9]/,""); print; exit}' "$file" 2>/dev/null)
    fi

    # Extract task text from "Tweaked Content" section (falls back to empty)
    local task_text=""
    task_text=$(awk '/^## Tweaked Content/{found=1; next} found && /^## /{exit} found && /^###/{exit} found{print}' "$file" 2>/dev/null | sed '/^$/d' | head -5 || true)
    # Strip leading/trailing whitespace; collapse newlines to single space
    task_text=$(printf '%s' "$task_text" | tr '\n' ' ' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//;s/  */ /g')

    printf '{"verdict":"%s","confidence":%s,"task_text":"%s"}' \
        "$(_json_escape "${verdict:-unknown}")" \
        "${confidence:-0}" \
        "$(_json_escape "${task_text}")"
}

# _parse_coder_summary FILE
# Extract status and file list from ${CODER_SUMMARY_FILE}.
# Handles: "## Status: COMPLETE", "## Status\nCOMPLETE", "Status: IN PROGRESS"
_parse_coder_summary() {
    local file="$1"
    [[ ! -f "$file" ]] && { echo "null"; return 0; }

    local status=""
    # Try inline "## Status: VALUE" (most common format)
    status=$(sed -n 's/^[#]* *Status[: ]*//p' "$file" 2>/dev/null | head -1 | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
    # Fallback: header then next line
    if [[ -z "$status" ]]; then
        status=$(awk '/^##? *Status *$/{getline; gsub(/^[[:space:]]+|[[:space:]]+$/,""); print; exit}' "$file" 2>/dev/null)
    fi

    local file_count=0
    file_count=$(awk '/^## Files ([Cc]reated|[Mm]odified)/{f=1;next} f && /^##/{exit} f && /^[-*]/{c++} END{print c+0}' \
        "$file" 2>/dev/null || echo "0")

    printf '{"status":"%s","files_modified":%s}' \
        "$(_json_escape "${status:-unknown}")" \
        "$file_count"
}

# _parse_reviewer_report FILE
# Extract verdict from ${REVIEWER_REPORT_FILE}.
_parse_reviewer_report() {
    local file="$1"
    [[ ! -f "$file" ]] && { echo "null"; return 0; }

    local verdict=""
    verdict=$(grep -m1 "^## Verdict" -A1 "$file" 2>/dev/null | tail -1 | tr -d '[:space:]' || true)

    printf '{"verdict":"%s"}' "$(_json_escape "${verdict:-unknown}")"
}

# --- Run summary parsers (sourced from dashboard_parsers_runs.sh) -----------
# shellcheck source=lib/dashboard_parsers_runs.sh
source "${BASH_SOURCE[0]%/*}/dashboard_parsers_runs.sh"
