#!/usr/bin/env bash
set -euo pipefail
# =============================================================================
# dashboard_emitters.sh — Dashboard data emitter functions
#
# Sourced by tekhton.sh — do not run directly.
# Expects: causality.sh, dashboard_parsers.sh, and dashboard.sh sourced first.
# Expects: PROJECT_DIR, TEKHTON_HOME (set by caller/config)
#
# Provides:
#   _regenerate_timeline_js    — rebuild data/timeline.js from causal log
#   emit_dashboard_milestones  — generate data/milestones.js
#   emit_dashboard_security    — generate data/security.js
#   emit_dashboard_reports     — generate data/reports.js
#   emit_dashboard_metrics     — generate data/metrics.js
#   emit_dashboard_health      — generate data/health.js
# =============================================================================

# --- Timeline emission --------------------------------------------------------

# _regenerate_timeline_js
# Rebuild data/timeline.js from the causal log.
# Respects DASHBOARD_MAX_TIMELINE_EVENTS cap.
_regenerate_timeline_js() {
    if ! is_dashboard_enabled; then return 0; fi

    local dash_dir="${PROJECT_DIR:-.}/${DASHBOARD_DIR:-.claude/dashboard}"
    [[ ! -d "${dash_dir}/data" ]] && return 0
    [[ ! -f "${CAUSAL_LOG_FILE:-}" ]] && return 0

    : "${DASHBOARD_MAX_TIMELINE_EVENTS:=500}"
    : "${DASHBOARD_VERBOSITY:=normal}"

    local tmpfile="${dash_dir}/data/timeline.js.tmp.$$"
    {
        printf '// Generated by Tekhton Watchtower — do not edit\n'
        printf '// Updated: %s\n' "$(_to_js_timestamp)"
        printf 'window.TK_TIMELINE = [\n'

        local count=0
        local first=true
        # Apply verbosity filter
        local filter_pattern=""
        case "$DASHBOARD_VERBOSITY" in
            minimal) filter_pattern='"type":"stage_end"\|"type":"verdict"' ;;
            normal)  filter_pattern='"type":"stage_\|"type":"verdict"\|"type":"finding"\|"type":"build_gate"\|"type":"pipeline_\|"type":"milestone_"' ;;
            verbose) filter_pattern="" ;;  # no filter — include everything
        esac

        # Read from causal log, apply filter, cap at max events
        # Use tail to get most recent events if log exceeds cap
        local lines
        if [[ -n "$filter_pattern" ]]; then
            lines=$(grep "$filter_pattern" "$CAUSAL_LOG_FILE" 2>/dev/null | tail -n "$DASHBOARD_MAX_TIMELINE_EVENTS" || true)
        else
            lines=$(tail -n "$DASHBOARD_MAX_TIMELINE_EVENTS" "$CAUSAL_LOG_FILE" 2>/dev/null || true)
        fi

        while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            if [[ "$first" = true ]]; then
                first=false
            else
                printf ',\n'
            fi
            printf '  %s' "$line"
            count=$(( count + 1 ))
        done <<< "$lines"

        printf '\n];\n'
    } > "$tmpfile"
    mv "$tmpfile" "${dash_dir}/data/timeline.js"
}

# --- Milestone emission -------------------------------------------------------

# emit_dashboard_milestones
# Reads MANIFEST.cfg and generates data/milestones.js.
emit_dashboard_milestones() {
    if ! is_dashboard_enabled; then return 0; fi

    local dash_dir="${PROJECT_DIR:-.}/${DASHBOARD_DIR:-.claude/dashboard}"
    [[ ! -d "${dash_dir}/data" ]] && return 0

    local manifest="${MILESTONE_DIR:-${PROJECT_DIR:-.}/.claude/milestones}/${MILESTONE_MANIFEST:-MANIFEST.cfg}"

    local json="["
    local first=true

    if [[ -f "$manifest" ]]; then
        while IFS='|' read -r mid title status deps _mfile pgroup; do
            # Skip comments and empty lines
            [[ -z "$mid" ]] && continue
            [[ "$mid" =~ ^[[:space:]]*# ]] && continue
            mid="${mid## }"; mid="${mid%% }"
            title="${title## }"; title="${title%% }"
            status="${status## }"; status="${status%% }"
            deps="${deps## }"; deps="${deps%% }"
            pgroup="${pgroup## }"; pgroup="${pgroup%% }"

            if [[ "$first" = true ]]; then first=false; else json="${json},"; fi
            json="${json}{\"id\":\"$(_json_escape "$mid")\",\"title\":\"$(_json_escape "$title")\",\"status\":\"$(_json_escape "$status")\",\"depends_on\":\"$(_json_escape "$deps")\",\"parallel_group\":\"$(_json_escape "$pgroup")\"}"
        done < "$manifest"
    fi

    json="${json}]"
    _write_js_file "${dash_dir}/data/milestones.js" "TK_MILESTONES" "$json"
}

# --- Security emission --------------------------------------------------------

# emit_dashboard_security
# Parses SECURITY_REPORT.md and generates data/security.js.
emit_dashboard_security() {
    if ! is_dashboard_enabled; then return 0; fi

    local dash_dir="${PROJECT_DIR:-.}/${DASHBOARD_DIR:-.claude/dashboard}"
    [[ ! -d "${dash_dir}/data" ]] && return 0

    local findings
    findings=$(_parse_security_report "${SECURITY_REPORT_FILE:-SECURITY_REPORT.md}")

    local json="{\"findings\":${findings}}"
    _write_js_file "${dash_dir}/data/security.js" "TK_SECURITY" "$json"
}

# --- Reports emission ---------------------------------------------------------

# emit_dashboard_reports
# Parses stage reports and generates data/reports.js.
emit_dashboard_reports() {
    if ! is_dashboard_enabled; then return 0; fi

    local dash_dir="${PROJECT_DIR:-.}/${DASHBOARD_DIR:-.claude/dashboard}"
    [[ ! -d "${dash_dir}/data" ]] && return 0

    local intake
    intake=$(_parse_intake_report "${INTAKE_REPORT_FILE:-INTAKE_REPORT.md}")
    local coder
    coder=$(_parse_coder_summary "CODER_SUMMARY.md")
    local reviewer
    reviewer=$(_parse_reviewer_report "REVIEWER_REPORT.md")

    local json
    json="{\"intake\":${intake},\"coder\":${coder},\"reviewer\":${reviewer}}"
    _write_js_file "${dash_dir}/data/reports.js" "TK_REPORTS" "$json"
}

# --- Metrics emission ---------------------------------------------------------

# emit_dashboard_metrics
# Reads RUN_SUMMARY.json files and generates data/metrics.js.
emit_dashboard_metrics() {
    if ! is_dashboard_enabled; then return 0; fi

    local dash_dir="${PROJECT_DIR:-.}/${DASHBOARD_DIR:-.claude/dashboard}"
    [[ ! -d "${dash_dir}/data" ]] && return 0

    local summary_dir="${LOG_DIR:-${PROJECT_DIR:-.}/.claude/logs}"
    local depth="${DASHBOARD_HISTORY_DEPTH:-50}"

    local runs
    runs=$(_parse_run_summaries "$summary_dir" "$depth")

    local json="{\"runs\":${runs}}"
    _write_js_file "${dash_dir}/data/metrics.js" "TK_METRICS" "$json"
}

# --- Health emission ----------------------------------------------------------

# emit_dashboard_health
# Reads HEALTH_BASELINE.json and generates data/health.js.
emit_dashboard_health() {
    if ! is_dashboard_enabled; then return 0; fi

    local dash_dir="${PROJECT_DIR:-.}/${DASHBOARD_DIR:-.claude/dashboard}"
    [[ ! -d "${dash_dir}/data" ]] && return 0

    local baseline_file="${PROJECT_DIR:-.}/${HEALTH_BASELINE_FILE:-.claude/HEALTH_BASELINE.json}"

    if [[ ! -f "$baseline_file" ]]; then
        _write_js_file "${dash_dir}/data/health.js" "TK_HEALTH" '{"available":false}'
        return 0
    fi

    # Read the JSON baseline directly — it's already valid JSON
    local baseline_content
    baseline_content=$(cat "$baseline_file" 2>/dev/null || echo "{}")

    # Wrap with metadata
    local belt=""
    if command -v get_health_belt &>/dev/null; then
        local composite
        composite=$(_read_json_int "$baseline_file" "composite")
        belt=$(get_health_belt "$composite")
    fi

    local json
    json="{\"available\":true,\"belt\":\"$(_json_escape "$belt")\",\"data\":${baseline_content}}"
    _write_js_file "${dash_dir}/data/health.js" "TK_HEALTH" "$json"
}
