#!/usr/bin/env bash
set -euo pipefail
# =============================================================================
# init_config_emitters.sh — Config file section emitters for Smart Init
#
# Sourced by init_config.sh — do not run directly.
# Depends on: common.sh (log, warn)
# =============================================================================

# --- Config file section emitters --------------------------------------------

_emit_header() {
    local project_name="$1"
    # Compute config version watermark from running Tekhton version (MAJOR.MINOR only)
    local config_version="${TEKHTON_VERSION%.*}"
    config_version="${config_version:-3.0}"
    cat << EOF
# =============================================================================
# pipeline.conf — Auto-generated by tekhton --init (Smart Init)
#
# Review all values below. Lines marked # VERIFY: were detected with medium
# confidence — double-check before your first pipeline run.
# Lines marked # SUGGESTION: were detected with low confidence.
# =============================================================================

# --- Tekhton config version (do not edit manually) ---------------------------
TEKHTON_CONFIG_VERSION="${config_version}"

# --- Project identity --------------------------------------------------------
PROJECT_NAME="${project_name}"
PROJECT_DESCRIPTION="(fill in a one-line description)"

EOF
}

_emit_tools() {
    local required_tools="$1"
    cat << EOF
# --- Required CLI tools (auto-detected) --------------------------------------
REQUIRED_TOOLS="${required_tools}"

EOF
}

_emit_models() {
    local coder_model="$1"
    cat << EOF
# --- Agent models ------------------------------------------------------------
CLAUDE_STANDARD_MODEL="claude-sonnet-4-6"
CLAUDE_CODER_MODEL="${coder_model}"
CLAUDE_JR_CODER_MODEL="claude-haiku-4-5"
CLAUDE_SCOUT_MODEL="claude-haiku-4-5"
CLAUDE_REVIEWER_MODEL="claude-sonnet-4-6"
CLAUDE_ARCHITECT_MODEL="claude-sonnet-4-6"
CLAUDE_TESTER_MODEL="claude-haiku-4-5"

EOF
}

_emit_turns() {
    local coder="$1" jr="$2" reviewer="$3" tester="$4" scout="$5"
    cat << EOF
# --- Turn limits (scaled by project size) ------------------------------------
CODER_MAX_TURNS=${coder}
JR_CODER_MAX_TURNS=${jr}
REVIEWER_MAX_TURNS=${reviewer}
TESTER_MAX_TURNS=${tester}
SCOUT_MAX_TURNS=${scout}
MAX_REVIEW_CYCLES=2

EOF
}

_emit_commands() {
    local test_cmd="$1" test_conf="$2"
    local analyze_cmd="$3" analyze_conf="$4"
    local build_cmd="$5" build_conf="$6"
    local test_source="${7:-}" analyze_source="${8:-}" build_source="${9:-}"

    echo "# --- Build / test / analyze commands ----------------------------------------"

    # TEST_CMD
    if [[ -n "$test_cmd" ]]; then
        _emit_command_line "TEST_CMD" "$test_cmd" "$test_conf" "$test_source"
    else
        echo '# Not auto-detected — fill in manually'
        echo 'TEST_CMD="true"'
    fi

    # ANALYZE_CMD
    if [[ -n "$analyze_cmd" ]]; then
        _emit_command_line "ANALYZE_CMD" "$analyze_cmd" "$analyze_conf" "$analyze_source"
    else
        echo '# Not auto-detected — fill in manually'
        echo "ANALYZE_CMD=\"echo 'No analyze command configured'\""
    fi

    # BUILD_CHECK_CMD
    if [[ -n "$build_cmd" ]]; then
        _emit_command_line "BUILD_CHECK_CMD" "$build_cmd" "$build_conf" "$build_source"
    else
        echo 'BUILD_CHECK_CMD=""'
    fi

    echo
}

# _emit_command_line — Emits a config line with confidence and source annotation.
# Args: $1=key, $2=cmd, $3=confidence, $4=source (optional)
_emit_command_line() {
    local key="$1"
    local cmd="$2"
    local conf="$3"
    local source="${4:-}"

    # Emit source annotation if available
    if [[ -n "$source" ]]; then
        echo "# Detected from: ${source} (confidence: ${conf})"
    fi

    case "$conf" in
        high)
            echo "${key}=\"${cmd}\""
            ;;
        medium)
            [[ -z "$source" ]] && echo "# VERIFY: detected with medium confidence"
            echo "${key}=\"${cmd}\""
            ;;
        low)
            echo "# SUGGESTION: detected with low confidence — uncomment if correct"
            echo "# ${key}=\"${cmd}\""
            echo "${key}=\"true\""
            ;;
        *)
            echo "${key}=\"${cmd}\""
            ;;
    esac
}

# _emit_workspace_config — Emits workspace/service/structure config (Milestone 12).
_emit_workspace_config() {
    local workspaces="${_INIT_WORKSPACES:-}"
    local services="${_INIT_SERVICES:-}"
    local workspace_scope="${_INIT_WORKSPACE_SCOPE:-}"

    # Determine project structure
    local project_structure="single"
    if [[ -n "$workspaces" ]]; then
        project_structure="monorepo"
    elif [[ -n "$services" ]]; then
        local svc_count
        svc_count=$(echo "$services" | grep -c '.' || echo "0")
        [[ "$svc_count" -gt 1 ]] && project_structure="multi-service"
    fi

    cat << EOF
# --- Project structure (Milestone 12) ----------------------------------------
PROJECT_STRUCTURE="${project_structure}"
EOF

    if [[ -n "$workspaces" ]]; then
        local ws_type
        ws_type=$(echo "$workspaces" | head -1 | cut -d'|' -f1)
        local ws_subs
        ws_subs=$(echo "$workspaces" | head -1 | cut -d'|' -f3)
        cat << EOF
WORKSPACE_TYPE="${ws_type}"
# WORKSPACE_SUBPROJECTS="${ws_subs}"
EOF
        if [[ -n "$workspace_scope" ]] && [[ "$workspace_scope" != "root" ]]; then
            cat << EOF
# Scoped to subproject: ${workspace_scope}
# WORKSPACE_SCOPE="${workspace_scope}"
EOF
        fi
    fi

    if [[ -n "$services" ]]; then
        echo "# Detected services:"
        while IFS='|' read -r name dir tech source; do
            [[ -z "$name" ]] && continue
            echo "# SERVICE: ${name} → ${dir} (${tech}, detected from ${source})"
        done <<< "$services"
    fi
    echo ""
}

_emit_paths() {
    local design_file="${1:-}"
    cat << EOF
# --- Tekhton artifact directory ----------------------------------------------
# All pipeline-managed files (reports, state, errors) live here.
# CLAUDE.md stays at the project root — Claude Code requires it there.
TEKHTON_DIR="${TEKHTON_DIR:-.tekhton}"

# --- Pipeline file paths -----------------------------------------------------
PIPELINE_STATE_FILE=".claude/PIPELINE_STATE.md"
LOG_DIR=".claude/logs"

# --- Agent role files --------------------------------------------------------
CODER_ROLE_FILE=".claude/agents/coder.md"
REVIEWER_ROLE_FILE=".claude/agents/reviewer.md"
TESTER_ROLE_FILE=".claude/agents/tester.md"
JR_CODER_ROLE_FILE=".claude/agents/jr-coder.md"
ARCHITECT_ROLE_FILE=".claude/agents/architect.md"

# --- Context files -----------------------------------------------------------
ARCHITECTURE_FILE=""
PROJECT_RULES_FILE="CLAUDE.md"
DESIGN_FILE="${design_file}"

# --- Drift detection ---------------------------------------------------------
DRIFT_LOG_FILE="${DRIFT_LOG_FILE:-${TEKHTON_DIR:-.tekhton}/DRIFT_LOG.md}"
ARCHITECTURE_LOG_FILE="${ARCHITECTURE_LOG_FILE:-${TEKHTON_DIR:-.tekhton}/ARCHITECTURE_LOG.md}"
HUMAN_ACTION_FILE="${HUMAN_ACTION_FILE:-${TEKHTON_DIR:-.tekhton}/HUMAN_ACTION_REQUIRED.md}"
DRIFT_OBSERVATION_THRESHOLD=8
DRIFT_RUNS_SINCE_AUDIT_THRESHOLD=5
NON_BLOCKING_LOG_FILE="${NON_BLOCKING_LOG_FILE:-${TEKHTON_DIR:-.tekhton}/NON_BLOCKING_LOG.md}"

# --- Dynamic turns -----------------------------------------------------------
DYNAMIC_TURNS_ENABLED=true

# --- Context budget ----------------------------------------------------------
CONTEXT_BUDGET_ENABLED=true
CONTEXT_BUDGET_PCT=50
CHARS_PER_TOKEN=4
EOF
}
