#!/usr/bin/env bash
set -euo pipefail
# =============================================================================
# init_config_sections.sh — Sectioned config file generator (Milestone 22)
#
# Replaces flat config emission with clearly separated sections.
# Essential config is in the first 15-20 lines so new users see what matters.
#
# Sourced by init_config.sh — do not run directly.
# Depends on: common.sh (log, warn)
# =============================================================================

# --- Section header helper ----------------------------------------------------

# _emit_section_header — Prints a section header with separator.
# Args: $1 = section number, $2 = title, $3 = description
_emit_section_header() {
    local num="$1"
    local title="$2"
    local desc="$3"
    cat << EOF

# ═══════════════════════════════════════════════════════════════════════════════
# Section ${num}: ${title}
# ${desc}
# ═══════════════════════════════════════════════════════════════════════════════

EOF
}

# --- Sectioned config emitters ------------------------------------------------

# _emit_section_essential — Section 1: Essential config (first ~20 lines).
# Args: $1=project_name, $2=test_cmd, $3=test_conf, $4=analyze_cmd,
#        $5=analyze_conf, $6=build_cmd, $7=build_conf, $8=design_file
_emit_section_essential() {
    local project_name="$1"
    local test_cmd="$2" test_conf="$3"
    local analyze_cmd="$4" analyze_conf="$5"
    local build_cmd="$6" build_conf="$7"
    local design_file="${8:-}"

    local config_version="${TEKHTON_VERSION%.*}"
    config_version="${config_version:-3.0}"

    cat << EOF
# Tekhton pipeline.conf — Auto-generated by tekhton --init
# Review these — auto-detected values may need adjustment
TEKHTON_CONFIG_VERSION="${config_version}"
PROJECT_NAME="${project_name}"
EOF

    # TEST_CMD
    if [[ -n "$test_cmd" ]]; then
        _emit_verified_line "TEST_CMD" "$test_cmd" "$test_conf"
    else
        echo '# No test command detected — set manually:'
        echo 'TEST_CMD="true"'
    fi

    # ANALYZE_CMD
    if [[ -n "$analyze_cmd" ]]; then
        _emit_verified_line "ANALYZE_CMD" "$analyze_cmd" "$analyze_conf"
    else
        echo "ANALYZE_CMD=\"echo 'No analyze command configured'\""
    fi

    # BUILD_CHECK_CMD
    if [[ -n "$build_cmd" ]]; then
        _emit_verified_line "BUILD_CHECK_CMD" "$build_cmd" "$build_conf"
    else
        echo 'BUILD_CHECK_CMD=""'
    fi

    echo "ARCHITECTURE_FILE=\"\""
    echo "PROJECT_RULES_FILE=\"CLAUDE.md\""
    if [[ -n "$design_file" ]]; then
        echo "DESIGN_FILE=\"${design_file}\""
    else
        echo 'DESIGN_FILE=""'
    fi
}

# _emit_verified_line — Emits a config key with VERIFY marker if needed.
# Args: $1=key, $2=value, $3=confidence
_emit_verified_line() {
    local key="$1" val="$2" conf="$3"
    case "$conf" in
        high)
            echo "${key}=\"${val}\""
            ;;
        medium)
            echo "# VERIFY: detected with medium confidence"
            echo "${key}=\"${val}\""
            ;;
        low)
            echo "# SUGGESTION: detected with low confidence — uncomment if correct"
            echo "# ${key}=\"${val}\""
            echo "${key}=\"true\""
            ;;
        *)
            echo "${key}=\"${val}\""
            ;;
    esac
}

# _emit_section_models_turns — Section 2: Models & Turns.
# Args: $1=coder_model, $2...$6=turn limits
_emit_section_models_turns() {
    local coder_model="$1"
    local coder_turns="$2" jr_turns="$3" reviewer_turns="$4"
    local tester_turns="$5" scout_turns="$6"

    _emit_section_header "2" "Models & Turns" \
        "Defaults work well — tune after a few runs if needed"

    cat << EOF
CLAUDE_STANDARD_MODEL="claude-sonnet-4-6"
CLAUDE_CODER_MODEL="${coder_model}"
CLAUDE_JR_CODER_MODEL="claude-haiku-4-5"
CLAUDE_SCOUT_MODEL="claude-haiku-4-5"
CLAUDE_REVIEWER_MODEL="claude-sonnet-4-6"
CLAUDE_ARCHITECT_MODEL="claude-sonnet-4-6"
CLAUDE_TESTER_MODEL="claude-haiku-4-5"

CODER_MAX_TURNS=${coder_turns}
JR_CODER_MAX_TURNS=${jr_turns}
REVIEWER_MAX_TURNS=${reviewer_turns}
TESTER_MAX_TURNS=${tester_turns}
SCOUT_MAX_TURNS=${scout_turns}
DYNAMIC_TURNS_ENABLED=true
EOF
}

# _emit_section_pipeline — Section 3: Pipeline Behavior.
_emit_section_pipeline() {
    local required_tools="$1"

    _emit_section_header "3" "Pipeline Behavior" \
        "Advanced — most users never change these"

    cat << EOF
REQUIRED_TOOLS="${required_tools}"
MAX_REVIEW_CYCLES=2
CONTEXT_BUDGET_ENABLED=true
CONTEXT_BUDGET_PCT=50
CHARS_PER_TOKEN=4
CONTEXT_COMPILER_ENABLED=false
# CLARIFICATION_ENABLED=true
# REPLAN_ENABLED=true
# CONTINUATION_ENABLED=true
# MAX_CONTINUATION_ATTEMPTS=3
EOF
}

# _emit_section_security — Section 4: Security.
_emit_section_security() {
    _emit_section_header "4" "Security" \
        "Security is ON by default — adjust policy to your risk tolerance"

    cat << EOF
# SPECIALIST_SECURITY_ENABLED=false
# SPECIALIST_SECURITY_MODEL="claude-sonnet-4-6"
# SPECIALIST_SECURITY_MAX_TURNS=8
# AGENT_SKIP_PERMISSIONS=false
EOF
}

# _emit_section_features — Section 5: Features.
_emit_section_features() {
    _emit_section_header "5" "Features" \
        "Optional features — enable as needed"

    cat << EOF
# REPO_MAP_ENABLED=false
# SERENA_ENABLED=false
# DASHBOARD_ENABLED=true
# CLEANUP_ENABLED=false
# SEED_CONTRACTS_ENABLED=false
# INTAKE_AGENT_ENABLED=true
# MILESTONE_DAG_ENABLED=true
# MILESTONE_SPLIT_ENABLED=true
# TEST_BASELINE_ENABLED=true
EOF
}

# _emit_section_quotas — Section 6: Quotas & Autonomy.
_emit_section_quotas() {
    _emit_section_header "6" "Quotas & Autonomy" \
        "Controls for autonomous mode (--complete, --auto-advance)"

    cat << EOF
# COMPLETE_MODE_ENABLED=true
# MAX_PIPELINE_ATTEMPTS=5
# AUTONOMOUS_TIMEOUT=7200
# MAX_AUTONOMOUS_AGENT_CALLS=20
# AUTO_ADVANCE_ENABLED=false
# AUTO_ADVANCE_LIMIT=3
# USAGE_THRESHOLD_PCT=0
EOF
}

# _emit_section_paths — Section 7: Paths (always needed, rarely changed).
_emit_section_paths() {
    _emit_section_header "7" "Paths & Files" \
        "File paths — rarely need changing"

    cat << EOF
PIPELINE_STATE_FILE=".claude/PIPELINE_STATE.md"
LOG_DIR=".claude/logs"
CODER_ROLE_FILE=".claude/agents/coder.md"
REVIEWER_ROLE_FILE=".claude/agents/reviewer.md"
TESTER_ROLE_FILE=".claude/agents/tester.md"
JR_CODER_ROLE_FILE=".claude/agents/jr-coder.md"
ARCHITECT_ROLE_FILE=".claude/agents/architect.md"
DRIFT_LOG_FILE="DRIFT_LOG.md"
ARCHITECTURE_LOG_FILE="ARCHITECTURE_LOG.md"
HUMAN_ACTION_FILE="HUMAN_ACTION_REQUIRED.md"
NON_BLOCKING_LOG_FILE="NON_BLOCKING_LOG.md"
EOF
}

# --- Workspace/structure section (conditional) --------------------------------

# _emit_section_workspace — Emits project structure config if monorepo detected.
_emit_section_workspace() {
    local workspaces="${_INIT_WORKSPACES:-}"
    local services="${_INIT_SERVICES:-}"
    local workspace_scope="${_INIT_WORKSPACE_SCOPE:-}"

    local project_structure="single"
    if [[ -n "$workspaces" ]]; then
        project_structure="monorepo"
    elif [[ -n "$services" ]]; then
        local svc_count
        svc_count=$(echo "$services" | grep -c '.' || echo "0")
        [[ "$svc_count" -gt 1 ]] && project_structure="multi-service"
    fi

    # Only emit if non-trivial structure detected
    if [[ "$project_structure" != "single" ]]; then
        echo ""
        echo "# --- Project structure -------------------------------------------------------"
        echo "PROJECT_STRUCTURE=\"${project_structure}\""

        if [[ -n "$workspaces" ]]; then
            local ws_type
            ws_type=$(echo "$workspaces" | head -1 | cut -d'|' -f1)
            echo "WORKSPACE_TYPE=\"${ws_type}\""
            if [[ -n "$workspace_scope" ]] && [[ "$workspace_scope" != "root" ]]; then
                echo "# WORKSPACE_SCOPE=\"${workspace_scope}\""
            fi
        fi

        if [[ -n "$services" ]]; then
            echo "# Detected services:"
            local name dir tech source
            while IFS='|' read -r name dir tech source; do
                [[ -z "$name" ]] && continue
                echo "# SERVICE: ${name} -> ${dir} (${tech}, detected from ${source})"
            done <<< "$services"
        fi
    fi
}

# --- Main sectioned config generator -----------------------------------------

# generate_sectioned_config — Produces the complete pipeline.conf with sections.
# Args: $1=project_name, $2=test_cmd, $3=test_conf, $4=analyze_cmd,
#        $5=analyze_conf, $6=build_cmd, $7=build_conf,
#        $8=coder_model, $9=coder_turns, $10=jr_turns,
#        $11=reviewer_turns, $12=tester_turns, $13=scout_turns,
#        $14=required_tools, $15=design_file
# Output: complete config file content to stdout
generate_sectioned_config() {
    local project_name="$1"
    local test_cmd="$2" test_conf="$3"
    local analyze_cmd="$4" analyze_conf="$5"
    local build_cmd="$6" build_conf="$7"
    local coder_model="$8"
    local coder_turns="$9" jr_turns="${10}" reviewer_turns="${11}"
    local tester_turns="${12}" scout_turns="${13}"
    local required_tools="${14}"
    local design_file="${15:-}"

    _emit_section_essential "$project_name" \
        "$test_cmd" "$test_conf" "$analyze_cmd" "$analyze_conf" \
        "$build_cmd" "$build_conf" "$design_file"

    _emit_section_models_turns "$coder_model" \
        "$coder_turns" "$jr_turns" "$reviewer_turns" "$tester_turns" "$scout_turns"

    _emit_section_pipeline "$required_tools"

    _emit_section_security

    _emit_section_features

    _emit_section_quotas

    _emit_section_paths

    _emit_section_workspace
}
