#!/usr/bin/env bash
set -euo pipefail
# =============================================================================
# init_config.sh — Config generation helpers for Smart Init (Milestone 19)
#
# Sourced by init.sh — do not run directly.
# Depends on: common.sh (log, warn)
# =============================================================================

# --- Config generation --------------------------------------------------------

# _generate_smart_config — Builds pipeline.conf from detection results.
# Args: $1 = project_dir, $2 = output_file,
#        $3 = languages, $4 = frameworks, $5 = commands, $6 = file_count
_generate_smart_config() {
    local project_dir="$1"
    local conf_file="$2"
    local languages="$3"
    local _frameworks="$4"
    local commands="$5"
    local file_count="${6:-0}"

    local project_name
    project_name=$(basename "$project_dir")

    # Extract detected commands by type (prefer highest confidence)
    local test_cmd analyze_cmd build_cmd
    local test_conf analyze_conf build_conf
    test_cmd=$(_best_command "$commands" "test")
    test_conf=$(_best_confidence "$commands" "test")
    analyze_cmd=$(_best_command "$commands" "analyze")
    analyze_conf=$(_best_confidence "$commands" "analyze")
    build_cmd=$(_best_command "$commands" "build")
    build_conf=$(_best_confidence "$commands" "build")

    # Detect required tools from languages
    local required_tools
    required_tools=$(_detect_required_tools "$languages")

    # Scale turns by project size
    local coder_turns jr_turns reviewer_turns tester_turns scout_turns
    local coder_model="claude-sonnet-4-6"
    if [[ "$file_count" -gt 200 ]]; then
        coder_turns=50; jr_turns=20; reviewer_turns=15; tester_turns=40; scout_turns=25
        coder_model="claude-opus-4-6"
    elif [[ "$file_count" -gt 50 ]]; then
        coder_turns=40; jr_turns=15; reviewer_turns=12; tester_turns=35; scout_turns=20
        coder_model="claude-opus-4-6"
    else
        coder_turns=35; jr_turns=15; reviewer_turns=10; tester_turns=30; scout_turns=20
    fi

    # Auto-detect DESIGN_FILE
    local design_file=""
    [[ -f "${project_dir}/DESIGN.md" ]] && design_file="DESIGN.md"

    # Write config file
    {
        _emit_header "$project_name"
        _emit_tools "$required_tools"
        _emit_models "$coder_model"
        _emit_turns "$coder_turns" "$jr_turns" "$reviewer_turns" "$tester_turns" "$scout_turns"
        _emit_commands "$test_cmd" "$test_conf" "$analyze_cmd" "$analyze_conf" "$build_cmd" "$build_conf"
        _emit_paths "$design_file"
    } > "$conf_file"
}

# --- Command extraction helpers -----------------------------------------------

# _best_command — Extracts the best command of a given type from detection output.
_best_command() {
    local commands="$1"
    local cmd_type="$2"
    [[ -z "$commands" ]] && return 0
    echo "$commands" | grep "^${cmd_type}|" | head -1 | cut -d'|' -f2 || true
}

# _best_confidence — Extracts the confidence of the best command of a given type.
_best_confidence() {
    local commands="$1"
    local cmd_type="$2"
    [[ -z "$commands" ]] && return 0
    echo "$commands" | grep "^${cmd_type}|" | head -1 | cut -d'|' -f4 || true
}

# --- Required tools detection -------------------------------------------------

_detect_required_tools() {
    local languages="$1"
    local tools="claude git"

    [[ -z "$languages" ]] && { echo "$tools"; return 0; }

    local lang
    while IFS='|' read -r lang _conf _manifest; do
        case "$lang" in
            typescript|javascript) tools="$tools node npm" ;;
            python)     tools="$tools python" ;;
            rust)       tools="$tools cargo" ;;
            go)         tools="$tools go" ;;
            ruby)       tools="$tools ruby" ;;
            dart)       tools="$tools dart" ;;
            java)       tools="$tools java" ;;
            kotlin)     tools="$tools java" ;;
            php)        tools="$tools php" ;;
            elixir)     tools="$tools elixir mix" ;;
            csharp)     tools="$tools dotnet" ;;
            swift)      tools="$tools swift" ;;
            haskell)    tools="$tools ghc" ;;
        esac
    done <<< "$languages"

    # Deduplicate
    echo "$tools" | tr ' ' '\n' | sort -u | tr '\n' ' ' | sed 's/ $//'
}

# --- Config file section emitters --------------------------------------------

_emit_header() {
    local project_name="$1"
    cat << EOF
# =============================================================================
# pipeline.conf — Auto-generated by tekhton --init (Smart Init)
#
# Review all values below. Lines marked # VERIFY: were detected with medium
# confidence — double-check before your first pipeline run.
# Lines marked # SUGGESTION: were detected with low confidence.
# =============================================================================

# --- Project identity --------------------------------------------------------
PROJECT_NAME="${project_name}"
PROJECT_DESCRIPTION="(fill in a one-line description)"

EOF
}

_emit_tools() {
    local required_tools="$1"
    cat << EOF
# --- Required CLI tools (auto-detected) --------------------------------------
REQUIRED_TOOLS="${required_tools}"

EOF
}

_emit_models() {
    local coder_model="$1"
    cat << EOF
# --- Agent models ------------------------------------------------------------
CLAUDE_STANDARD_MODEL="claude-sonnet-4-6"
CLAUDE_CODER_MODEL="${coder_model}"
CLAUDE_JR_CODER_MODEL="claude-haiku-4-5"
CLAUDE_SCOUT_MODEL="claude-haiku-4-5"
CLAUDE_REVIEWER_MODEL="claude-sonnet-4-6"
CLAUDE_ARCHITECT_MODEL="claude-sonnet-4-6"
CLAUDE_TESTER_MODEL="claude-haiku-4-5"

EOF
}

_emit_turns() {
    local coder="$1" jr="$2" reviewer="$3" tester="$4" scout="$5"
    cat << EOF
# --- Turn limits (scaled by project size) ------------------------------------
CODER_MAX_TURNS=${coder}
JR_CODER_MAX_TURNS=${jr}
REVIEWER_MAX_TURNS=${reviewer}
TESTER_MAX_TURNS=${tester}
SCOUT_MAX_TURNS=${scout}
MAX_REVIEW_CYCLES=2

EOF
}

_emit_commands() {
    local test_cmd="$1" test_conf="$2"
    local analyze_cmd="$3" analyze_conf="$4"
    local build_cmd="$5" build_conf="$6"

    echo "# --- Build / test / analyze commands ----------------------------------------"

    # TEST_CMD
    if [[ -n "$test_cmd" ]]; then
        _emit_command_line "TEST_CMD" "$test_cmd" "$test_conf"
    else
        echo '# No test command detected — set manually:'
        echo 'TEST_CMD="true"'
    fi

    # ANALYZE_CMD
    if [[ -n "$analyze_cmd" ]]; then
        _emit_command_line "ANALYZE_CMD" "$analyze_cmd" "$analyze_conf"
    else
        echo '# No analyze command detected — set manually:'
        echo "ANALYZE_CMD=\"echo 'No analyze command configured'\""
    fi

    # BUILD_CHECK_CMD
    if [[ -n "$build_cmd" ]]; then
        _emit_command_line "BUILD_CHECK_CMD" "$build_cmd" "$build_conf"
    else
        echo 'BUILD_CHECK_CMD=""'
    fi

    echo
}

# _emit_command_line — Emits a config line with confidence annotation.
_emit_command_line() {
    local key="$1"
    local cmd="$2"
    local conf="$3"

    case "$conf" in
        high)
            echo "${key}=\"${cmd}\""
            ;;
        medium)
            echo "# VERIFY: detected with medium confidence"
            echo "${key}=\"${cmd}\""
            ;;
        low)
            echo "# SUGGESTION: detected with low confidence — uncomment if correct"
            echo "# ${key}=\"${cmd}\""
            echo "${key}=\"true\""
            ;;
        *)
            echo "${key}=\"${cmd}\""
            ;;
    esac
}

_emit_paths() {
    local design_file="${1:-}"
    cat << EOF
# --- Pipeline file paths -----------------------------------------------------
PIPELINE_STATE_FILE=".claude/PIPELINE_STATE.md"
LOG_DIR=".claude/logs"

# --- Agent role files --------------------------------------------------------
CODER_ROLE_FILE=".claude/agents/coder.md"
REVIEWER_ROLE_FILE=".claude/agents/reviewer.md"
TESTER_ROLE_FILE=".claude/agents/tester.md"
JR_CODER_ROLE_FILE=".claude/agents/jr-coder.md"
ARCHITECT_ROLE_FILE=".claude/agents/architect.md"

# --- Context files -----------------------------------------------------------
ARCHITECTURE_FILE=""
PROJECT_RULES_FILE="CLAUDE.md"
DESIGN_FILE="${design_file}"

# --- Drift detection ---------------------------------------------------------
DRIFT_LOG_FILE="DRIFT_LOG.md"
ARCHITECTURE_LOG_FILE="ARCHITECTURE_LOG.md"
HUMAN_ACTION_FILE="HUMAN_ACTION_REQUIRED.md"
DRIFT_OBSERVATION_THRESHOLD=8
DRIFT_RUNS_SINCE_AUDIT_THRESHOLD=5
NON_BLOCKING_LOG_FILE="NON_BLOCKING_LOG.md"

# --- Dynamic turns -----------------------------------------------------------
DYNAMIC_TURNS_ENABLED=true

# --- Context budget ----------------------------------------------------------
CONTEXT_BUDGET_ENABLED=true
CONTEXT_BUDGET_PCT=50
CHARS_PER_TOKEN=4
EOF
}
