#!/usr/bin/env bash
set -euo pipefail
# =============================================================================
# init_config_sections.sh — Sectioned config file generator (Milestone 22)
#
# Replaces flat config emission with clearly separated sections.
# Essential config is in the first 15-20 lines so new users see what matters.
#
# Sourced by init_config.sh — do not run directly.
# Depends on: common.sh (log, warn)
# =============================================================================

# _emit_section_header — Prints a section header with separator.
_emit_section_header() {
    local num="$1"
    local title="$2"
    local desc="$3"
    cat << EOF

# ═══════════════════════════════════════════════════════════════════════════════
# Section ${num}: ${title}
# ${desc}
# ═══════════════════════════════════════════════════════════════════════════════

EOF
}

# _emit_section_essential — Section 1: Essential config (first ~20 lines).
# Args: $1=project_name, $2=test_cmd, $3=test_conf, $4=analyze_cmd,
#        $5=analyze_conf, $6=build_cmd, $7=build_conf, $8=design_file,
#        $9=test_source, $10=analyze_source, $11=build_source
_emit_section_essential() {
    local project_name="$1"
    local test_cmd="$2" test_conf="$3"
    local analyze_cmd="$4" analyze_conf="$5"
    local build_cmd="$6" build_conf="$7"
    local design_file="${8:-}"
    local test_source="${9:-}" analyze_source="${10:-}" build_source="${11:-}"

    local config_version="${TEKHTON_VERSION%.*}"
    config_version="${config_version:-3.0}"

    cat << EOF
# Tekhton pipeline.conf — Auto-generated by tekhton --init
# Review these — auto-detected values may need adjustment
TEKHTON_CONFIG_VERSION="${config_version}"
PROJECT_NAME="${project_name}"
# Not auto-detected — fill in manually
# PROJECT_DESCRIPTION="(fill in a one-line description)"
EOF

    # TEST_CMD
    if [[ -n "$test_cmd" ]]; then
        _emit_verified_line "TEST_CMD" "$test_cmd" "$test_conf" "$test_source"
    else
        echo '# Not auto-detected — fill in manually'
        echo 'TEST_CMD="true"'
    fi

    # ANALYZE_CMD
    if [[ -n "$analyze_cmd" ]]; then
        _emit_verified_line "ANALYZE_CMD" "$analyze_cmd" "$analyze_conf" "$analyze_source"
    else
        echo '# Not auto-detected — fill in manually'
        echo "ANALYZE_CMD=\"echo 'No analyze command configured'\""
    fi

    # BUILD_CHECK_CMD
    if [[ -n "$build_cmd" ]]; then
        _emit_verified_line "BUILD_CHECK_CMD" "$build_cmd" "$build_conf" "$build_source"
    else
        echo 'BUILD_CHECK_CMD=""'
    fi

    echo "ARCHITECTURE_FILE=\"\""
    echo "PROJECT_RULES_FILE=\"CLAUDE.md\""
    if [[ -n "$design_file" ]]; then
        echo "DESIGN_FILE=\"${design_file}\""
    else
        echo 'DESIGN_FILE=""'
    fi
}

# _emit_verified_line — Emits a config key with source annotation and VERIFY marker.
# Args: $1=key, $2=value, $3=confidence, $4=source (optional)
_emit_verified_line() {
    local key="$1" val="$2" conf="$3" source="${4:-}"

    # Emit source annotation if available
    if [[ -n "$source" ]]; then
        echo "# Detected from: ${source} (confidence: ${conf})"
    fi

    case "$conf" in
        high)
            echo "${key}=\"${val}\""
            ;;
        medium)
            [[ -z "$source" ]] && echo "# VERIFY: detected with medium confidence"
            echo "${key}=\"${val}\""
            ;;
        low)
            echo "# SUGGESTION: detected with low confidence — uncomment if correct"
            echo "# ${key}=\"${val}\""
            echo "${key}=\"true\""
            ;;
        *)
            echo "${key}=\"${val}\""
            ;;
    esac
}

# _emit_section_models_turns — Section 2: Models & Turns.
# Args: $1=coder_model, $2...$6=turn limits
_emit_section_models_turns() {
    local coder_model="$1"
    local coder_turns="$2" jr_turns="$3" reviewer_turns="$4"
    local tester_turns="$5" scout_turns="$6"

    _emit_section_header "2" "Models & Turns" \
        "Defaults work well — tune after a few runs if needed"

    cat << EOF
CLAUDE_STANDARD_MODEL="claude-sonnet-4-6"
CLAUDE_CODER_MODEL="${coder_model}"
CLAUDE_JR_CODER_MODEL="claude-haiku-4-5"
CLAUDE_SCOUT_MODEL="claude-haiku-4-5"
CLAUDE_REVIEWER_MODEL="claude-sonnet-4-6"
CLAUDE_ARCHITECT_MODEL="claude-sonnet-4-6"
CLAUDE_TESTER_MODEL="claude-haiku-4-5"

CODER_MAX_TURNS=${coder_turns}
JR_CODER_MAX_TURNS=${jr_turns}
REVIEWER_MAX_TURNS=${reviewer_turns}
TESTER_MAX_TURNS=${tester_turns}
SCOUT_MAX_TURNS=${scout_turns}
DYNAMIC_TURNS_ENABLED=true
EOF
}

# _emit_section_pipeline — Section 3: Pipeline Behavior.
_emit_section_pipeline() {
    local required_tools="$1"

    _emit_section_header "3" "Pipeline Behavior" \
        "Advanced — most users never change these"

    cat << EOF
REQUIRED_TOOLS="${required_tools}"
MAX_REVIEW_CYCLES=2
CONTEXT_BUDGET_ENABLED=true
CONTEXT_BUDGET_PCT=50
CHARS_PER_TOKEN=4
CONTEXT_COMPILER_ENABLED=false
# CLARIFICATION_ENABLED=true
# REPLAN_ENABLED=true
# CONTINUATION_ENABLED=true
# MAX_CONTINUATION_ATTEMPTS=3
EOF
}

# _emit_section_security — Section 4: Security.
_emit_section_security() {
    _emit_section_header "4" "Security" \
        "Security is ON by default — adjust policy to your risk tolerance"

    cat << EOF
# SPECIALIST_SECURITY_ENABLED=false
# SPECIALIST_SECURITY_MODEL="claude-sonnet-4-6"
# SPECIALIST_SECURITY_MAX_TURNS=8
# AGENT_SKIP_PERMISSIONS=false
EOF
}

# _emit_section_features — Section 5: Features.
# When the M109 wizard set _WIZARD_*_ENABLED env vars, those features are
# emitted as uncommented active lines; otherwise they remain commented out
# (today's behavior). DASHBOARD_ENABLED is always emitted active.
_emit_section_features() {
    _emit_section_header "5" "Features" \
        "Optional features — enable as needed"

    if [[ "${_WIZARD_TUI_ENABLED:-}" == "true" ]]; then
        echo "TUI_ENABLED=true"
    elif [[ "${_WIZARD_TUI_ENABLED:-}" == "auto" ]]; then
        echo "TUI_ENABLED=auto"
    else
        echo "# TUI_ENABLED=auto"
    fi

    if [[ "${_WIZARD_REPO_MAP_ENABLED:-}" == "true" ]]; then
        echo "REPO_MAP_ENABLED=true"
    else
        echo "# REPO_MAP_ENABLED=false"
    fi

    if [[ "${_WIZARD_SERENA_ENABLED:-}" == "true" ]]; then
        echo "SERENA_ENABLED=true"
    else
        echo "# SERENA_ENABLED=false"
    fi

    echo "DASHBOARD_ENABLED=true"

    cat << EOF
# CLEANUP_ENABLED=false
# SEED_CONTRACTS_ENABLED=false
# INTAKE_AGENT_ENABLED=true
# MILESTONE_DAG_ENABLED=true
# MILESTONE_SPLIT_ENABLED=true
# TEST_BASELINE_ENABLED=true
EOF
}

# _emit_section_quotas — Section 6: Quotas & Autonomy.
_emit_section_quotas() {
    _emit_section_header "6" "Quotas & Autonomy" \
        "Controls for autonomous mode (--complete, --auto-advance)"

    cat << EOF
# COMPLETE_MODE_ENABLED=true
# MAX_PIPELINE_ATTEMPTS=5
# AUTONOMOUS_TIMEOUT=7200
# MAX_AUTONOMOUS_AGENT_CALLS=20
# AUTO_ADVANCE_ENABLED=false
# AUTO_ADVANCE_LIMIT=3
# USAGE_THRESHOLD_PCT=0
EOF
}

# _emit_section_paths — Section 7: Paths (always needed, rarely changed).
_emit_section_paths() {
    _emit_section_header "7" "Paths & Files" \
        "File paths — rarely need changing"

    cat << EOF
TEKHTON_DIR="${TEKHTON_DIR:-.tekhton}"
PIPELINE_STATE_FILE=".claude/PIPELINE_STATE.md"
LOG_DIR=".claude/logs"
CODER_ROLE_FILE=".claude/agents/coder.md"
REVIEWER_ROLE_FILE=".claude/agents/reviewer.md"
TESTER_ROLE_FILE=".claude/agents/tester.md"
JR_CODER_ROLE_FILE=".claude/agents/jr-coder.md"
ARCHITECT_ROLE_FILE=".claude/agents/architect.md"
DRIFT_LOG_FILE="${DRIFT_LOG_FILE:-${TEKHTON_DIR:-.tekhton}/DRIFT_LOG.md}"
ARCHITECTURE_LOG_FILE="${ARCHITECTURE_LOG_FILE:-${TEKHTON_DIR:-.tekhton}/ARCHITECTURE_LOG.md}"
HUMAN_ACTION_FILE="${HUMAN_ACTION_FILE:-${TEKHTON_DIR:-.tekhton}/HUMAN_ACTION_REQUIRED.md}"
NON_BLOCKING_LOG_FILE="${NON_BLOCKING_LOG_FILE:-${TEKHTON_DIR:-.tekhton}/NON_BLOCKING_LOG.md}"
EOF
}

# shellcheck source=init_config_workspace.sh disable=SC1091
source "$(dirname "${BASH_SOURCE[0]}")/init_config_workspace.sh"

# generate_sectioned_config — Produces the complete pipeline.conf with sections.
# Args: $1=project_name, $2=test_cmd, $3=test_conf, $4=analyze_cmd,
#        $5=analyze_conf, $6=build_cmd, $7=build_conf,
#        $8=coder_model, $9=coder_turns, $10=jr_turns,
#        $11=reviewer_turns, $12=tester_turns, $13=scout_turns,
#        $14=required_tools, $15=design_file,
#        $16=test_source, $17=analyze_source, $18=build_source
# Output: complete config file content to stdout
generate_sectioned_config() {
    local project_name="$1"
    local test_cmd="$2" test_conf="$3"
    local analyze_cmd="$4" analyze_conf="$5"
    local build_cmd="$6" build_conf="$7"
    local coder_model="$8"
    local coder_turns="$9" jr_turns="${10}" reviewer_turns="${11}"
    local tester_turns="${12}" scout_turns="${13}"
    local required_tools="${14}"
    local design_file="${15:-}"
    local test_source="${16:-}" analyze_source="${17:-}" build_source="${18:-}"

    _emit_section_essential "$project_name" \
        "$test_cmd" "$test_conf" "$analyze_cmd" "$analyze_conf" \
        "$build_cmd" "$build_conf" "$design_file" \
        "$test_source" "$analyze_source" "$build_source"

    _emit_section_models_turns "$coder_model" \
        "$coder_turns" "$jr_turns" "$reviewer_turns" "$tester_turns" "$scout_turns"

    _emit_section_pipeline "$required_tools"

    _emit_section_security

    _emit_section_features

    _emit_section_quotas

    _emit_section_paths

    _emit_section_workspace
}
