// coverage_test.go — tests for gaps identified in the m33.1 reviewer report:
//   - concurrent atomicity of jsfile.go (milestone AC: 100 concurrent reads
//     while writing 100 times; reader sees only fully-formed JS files)
//   - EmitDiagnosis available=true path (LAST_FAILURE_CONTEXT.json present)
//   - EmitTeamState: errEmptyTeamID sentinel + delegation to EmitRunState

package dashboard

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
)

// TestWriteJSFile_ConcurrentAtomicity verifies that the tempfile+os.Rename
// write discipline prevents readers from ever seeing a partial file.
// Milestone AC: "spawn 100 concurrent reads while writing 100 times; reader
// sees only fully-formed JS files."
func TestWriteJSFile_ConcurrentAtomicity(t *testing.T) {
	tmp := t.TempDir()
	target := filepath.Join(tmp, "run_state.js")

	// Seed the file so readers have valid content before the first write races.
	if err := WriteJSFile(target, "TK_RUN_STATE",
		map[string]any{"pipeline_status": "initializing"}, fixedTime); err != nil {
		t.Fatalf("seed: %v", err)
	}

	const n = 100
	var wg sync.WaitGroup
	// Buffered so senders never block even if the test ends early.
	errCh := make(chan string, n*2)

	// Close this to release all goroutines as simultaneously as Go allows.
	start := make(chan struct{})

	// n concurrent writers.
	for i := 0; i < n; i++ {
		wg.Add(1)
		go func(idx int) {
			defer wg.Done()
			<-start
			payload := map[string]any{"pipeline_status": "running", "seq": idx}
			if err := WriteJSFile(target, "TK_RUN_STATE", payload, fixedTime); err != nil {
				errCh <- fmt.Sprintf("writer %d: %v", idx, err)
			}
		}(i)
	}

	// n concurrent readers.  Each non-empty read must be a fully-formed file.
	for i := 0; i < n; i++ {
		wg.Add(1)
		go func(idx int) {
			defer wg.Done()
			<-start
			body, err := os.ReadFile(target)
			if err != nil {
				// Tolerate a transient ENOENT racing with the first rename.
				return
			}
			s := string(body)
			if s == "" {
				return
			}
			// The generated header must be the very first bytes — any other
			// prefix means a partial write slipped through the rename guard.
			if !strings.HasPrefix(s, "// Generated by Tekhton") {
				errCh <- fmt.Sprintf("reader %d: partial write — header missing: %q",
					idx, s[:min(80, len(s))])
				return
			}
			// If the variable-assignment line is present the JSON must parse.
			if i2 := strings.Index(s, " = "); i2 >= 0 {
				rest := s[i2+3:]
				semi := strings.LastIndex(rest, ";")
				if semi < 0 {
					errCh <- fmt.Sprintf("reader %d: missing trailing semicolon; body: %q",
						idx, s[:min(200, len(s))])
					return
				}
				var doc map[string]any
				if jsonErr := json.Unmarshal([]byte(rest[:semi]), &doc); jsonErr != nil {
					errCh <- fmt.Sprintf("reader %d: invalid JSON: %v; body: %q",
						idx, jsonErr, s[:min(200, len(s))])
				}
			}
		}(i)
	}

	close(start) // release all goroutines
	wg.Wait()
	close(errCh)

	for msg := range errCh {
		t.Error(msg)
	}
}

// TestEmitDiagnosis_WithFailureContext verifies the available=true path:
// when LAST_FAILURE_CONTEXT.json exists, EmitDiagnosis must emit
// available=true along with the classification, stage, and summary fields.
// This is the primary happy path; the missing-file path is just a fallback.
func TestEmitDiagnosis_WithFailureContext(t *testing.T) {
	tmp := t.TempDir()
	if err := Init(tmp, "", ""); err != nil {
		t.Fatalf("Init: %v", err)
	}

	// Plant the failure context fixture under <projectDir>/.claude/.
	ctxDir := filepath.Join(tmp, ".claude")
	if err := os.MkdirAll(ctxDir, 0o755); err != nil {
		t.Fatalf("mkdir .claude: %v", err)
	}
	fixture := `{"classification":"code_dominant","stage":"security","summary":"High severity finding in auth module"}`
	if err := os.WriteFile(filepath.Join(ctxDir, "LAST_FAILURE_CONTEXT.json"),
		[]byte(fixture), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	e := &Emitter{
		ProjectDir: tmp,
		DashDir:    filepath.Join(tmp, ".claude", "dashboard"),
		Enabled:    true,
		Now:        fixedTime,
	}
	if err := e.EmitDiagnosis(); err != nil {
		t.Fatalf("EmitDiagnosis: %v", err)
	}

	body, err := os.ReadFile(filepath.Join(e.DashDir, "data", "diagnosis.js"))
	if err != nil {
		t.Fatalf("read diagnosis.js: %v", err)
	}
	s := string(body)

	const assign = "window.TK_DIAGNOSIS = "
	idx := strings.Index(s, assign)
	if idx < 0 {
		t.Fatalf("missing %s assignment; body:\n%s", assign, s)
	}
	rest := s[idx+len(assign):]
	semi := strings.LastIndex(rest, ";")
	if semi < 0 {
		t.Fatalf("missing trailing semicolon; rest: %s", rest)
	}
	var doc map[string]any
	if err := json.Unmarshal([]byte(rest[:semi]), &doc); err != nil {
		t.Fatalf("invalid JSON: %v; payload: %s", err, rest[:semi])
	}

	if got := doc["available"]; got != true {
		t.Errorf("available: want true, got %v", got)
	}
	if got := doc["classification"]; got != "code_dominant" {
		t.Errorf("classification: want code_dominant, got %v", got)
	}
	if got := doc["stage"]; got != "security" {
		t.Errorf("stage: want security, got %v", got)
	}
	if got, ok := doc["summary"].(string); !ok || !strings.Contains(got, "auth module") {
		t.Errorf("summary: want string containing 'auth module', got %v", doc["summary"])
	}
}

// TestEmitDiagnosis_MissingContext verifies the available=false fallback when
// no LAST_FAILURE_CONTEXT.json is present.
func TestEmitDiagnosis_MissingContext(t *testing.T) {
	tmp := t.TempDir()
	if err := Init(tmp, "", ""); err != nil {
		t.Fatalf("Init: %v", err)
	}
	e := &Emitter{
		ProjectDir: tmp,
		DashDir:    filepath.Join(tmp, ".claude", "dashboard"),
		Enabled:    true,
		Now:        fixedTime,
	}
	if err := e.EmitDiagnosis(); err != nil {
		t.Fatalf("EmitDiagnosis: %v", err)
	}
	body, _ := os.ReadFile(filepath.Join(e.DashDir, "data", "diagnosis.js"))
	if !strings.Contains(string(body), `"available":false`) {
		t.Errorf("expected available=false in diagnosis.js; body:\n%s", body)
	}
}

// TestEmitTeamState_ErrorOnEmptyTeamID verifies the errEmptyTeamID sentinel
// is returned when an empty string is passed as the team ID.
func TestEmitTeamState_ErrorOnEmptyTeamID(t *testing.T) {
	e := &Emitter{Enabled: true, Now: fixedTime}
	err := e.EmitTeamState("")
	if !errors.Is(err, errEmptyTeamID) {
		t.Errorf("want errEmptyTeamID, got: %v", err)
	}
}

// TestEmitTeamState_DelegatesToEmitRunState verifies that a non-empty teamID
// succeeds, writes a valid run_state.js, and sets parallel_mode=true with the
// team present in the teams map.
func TestEmitTeamState_DelegatesToEmitRunState(t *testing.T) {
	tmp := t.TempDir()
	if err := Init(tmp, "", ""); err != nil {
		t.Fatalf("Init: %v", err)
	}
	e := &Emitter{
		ProjectDir:     tmp,
		DashDir:        filepath.Join(tmp, ".claude", "dashboard"),
		Enabled:        true,
		PipelineStatus: "running",
		CurrentStage:   "tester",
		ParallelTeams:  []string{"t1"},
		TeamStage:      map[string]string{"t1": "tester"},
		TeamStatus:     map[string]string{"t1": "running"},
		// Nil stage-level team maps — Go nil map reads return zero value safely.
		Now: fixedTime,
	}
	if err := e.EmitTeamState("t1"); err != nil {
		t.Fatalf("EmitTeamState(t1): %v", err)
	}
	body, err := os.ReadFile(filepath.Join(e.DashDir, "data", "run_state.js"))
	if err != nil {
		t.Fatalf("read run_state.js: %v", err)
	}
	s := string(body)
	if !strings.Contains(s, `"parallel_mode":true`) {
		t.Errorf("parallel_mode not true; body:\n%s", s)
	}
	if !strings.Contains(s, `"t1"`) {
		t.Errorf("team t1 missing from teams map; body:\n%s", s)
	}
}
