package dashboard

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func fixedTime() time.Time {
	return time.Date(2026, 5, 29, 18, 0, 0, 0, time.UTC)
}

func TestInit_SeedsTenDataFiles(t *testing.T) {
	tmp := t.TempDir()
	if err := Init(tmp, "", ""); err != nil {
		t.Fatalf("Init: %v", err)
	}
	wantFiles := []string{
		"run_state.js", "timeline.js", "milestones.js", "security.js",
		"reports.js", "metrics.js", "health.js", "diagnosis.js",
		"inbox.js", "notes.js",
	}
	for _, name := range wantFiles {
		path := filepath.Join(tmp, ".claude", "dashboard", "data", name)
		body, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("missing seed file %s: %v", name, err)
			continue
		}
		if !strings.HasPrefix(string(body), "// Generated by Tekhton") {
			t.Errorf("seed %s missing JS header: %q", name, string(body)[:min(40, len(body))])
		}
	}
}

func TestInit_PreservesExistingFiles(t *testing.T) {
	tmp := t.TempDir()
	if err := Init(tmp, "", ""); err != nil {
		t.Fatalf("first Init: %v", err)
	}
	// Mutate one seed; re-init should NOT clobber it.
	runStatePath := filepath.Join(tmp, ".claude", "dashboard", "data", "run_state.js")
	if err := os.WriteFile(runStatePath, []byte("custom data"), 0o644); err != nil {
		t.Fatalf("mutate seed: %v", err)
	}
	if err := Init(tmp, "", ""); err != nil {
		t.Fatalf("second Init: %v", err)
	}
	body, err := os.ReadFile(runStatePath)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if string(body) != "custom data" {
		t.Fatalf("Init clobbered existing file; got %q", body)
	}
}

func TestCleanup_RemovesTree(t *testing.T) {
	tmp := t.TempDir()
	if err := Init(tmp, "", ""); err != nil {
		t.Fatalf("Init: %v", err)
	}
	if err := Cleanup(tmp, ""); err != nil {
		t.Fatalf("Cleanup: %v", err)
	}
	if _, err := os.Stat(filepath.Join(tmp, ".claude", "dashboard")); !os.IsNotExist(err) {
		t.Fatalf("dashboard dir not removed: err=%v", err)
	}
}

func TestCleanup_IdempotentOnMissing(t *testing.T) {
	tmp := t.TempDir()
	// Cleanup with no Init — must not error.
	if err := Cleanup(tmp, ""); err != nil {
		t.Fatalf("Cleanup on missing dir: %v", err)
	}
}

func TestEnabled(t *testing.T) {
	if !Enabled("") {
		t.Error("Enabled(\"\") should be true (default-on)")
	}
	if !Enabled("true") {
		t.Error("Enabled(\"true\") should be true")
	}
	if Enabled("false") {
		t.Error("Enabled(\"false\") should be false")
	}
}

func TestEmitRunState_ValidatesAgainstProto(t *testing.T) {
	tmp := t.TempDir()
	if err := Init(tmp, "", ""); err != nil {
		t.Fatalf("Init: %v", err)
	}
	e := &Emitter{
		ProjectDir:       tmp,
		DashDir:          filepath.Join(tmp, ".claude", "dashboard"),
		Enabled:          true,
		PipelineStatus:   "running",
		CurrentStage:     "coder",
		CurrentMilestone: "m33.1",
		MilestoneTitle:   "Dashboard Emitters",
		StartedAt:        "2026-05-29T17:00:00Z",
		StageStatus:      map[string]string{"coder": "active"},
		StageTurns:       map[string]int{"coder": 5},
		StageBudget:      map[string]int{"coder": 50},
		StageDuration:    map[string]int{"coder": 120},
		DashboardRefresh: 5,
		Now:              fixedTime,
	}
	if err := e.EmitRunState(); err != nil {
		t.Fatalf("EmitRunState: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(e.DashDir, "data", "run_state.js"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	// Extract JSON between window.TK_RUN_STATE = and the trailing semicolon.
	s := string(body)
	idx := strings.Index(s, "window.TK_RUN_STATE = ")
	if idx < 0 {
		t.Fatalf("missing assignment: %s", s)
	}
	rest := s[idx+len("window.TK_RUN_STATE = "):]
	end := strings.LastIndex(rest, ";")
	if end < 0 {
		t.Fatalf("missing semicolon: %s", rest)
	}
	var doc map[string]any
	if err := json.Unmarshal([]byte(rest[:end]), &doc); err != nil {
		t.Fatalf("invalid JSON in emitted file: %v\npayload: %s", err, rest[:end])
	}
	if doc["pipeline_status"] != "running" {
		t.Errorf("pipeline_status: got %v", doc["pipeline_status"])
	}
	if doc["current_stage"] != "coder" {
		t.Errorf("current_stage: got %v", doc["current_stage"])
	}
	// Verify the active_milestone object is set.
	ms, ok := doc["active_milestone"].(map[string]any)
	if !ok {
		t.Fatalf("active_milestone not an object: %T %v", doc["active_milestone"], doc["active_milestone"])
	}
	if ms["id"] != "m33.1" {
		t.Errorf("milestone id: got %v", ms["id"])
	}
}

func TestEmitRunState_NoOpWhenDisabled(t *testing.T) {
	tmp := t.TempDir()
	if err := Init(tmp, "", ""); err != nil {
		t.Fatalf("Init: %v", err)
	}
	// Mutate the seed so we can detect whether Emit overwrote it.
	runStatePath := filepath.Join(tmp, ".claude", "dashboard", "data", "run_state.js")
	if err := os.WriteFile(runStatePath, []byte("sentinel"), 0o644); err != nil {
		t.Fatalf("mutate: %v", err)
	}
	e := &Emitter{
		ProjectDir: tmp,
		DashDir:    filepath.Join(tmp, ".claude", "dashboard"),
		Enabled:    false,
	}
	if err := e.EmitRunState(); err != nil {
		t.Fatalf("EmitRunState: %v", err)
	}
	body, _ := os.ReadFile(runStatePath)
	if string(body) != "sentinel" {
		t.Fatalf("Emit ran despite Enabled=false; body=%q", body)
	}
}

func TestEmitNotes_EmptyFileGivesBareArray(t *testing.T) {
	tmp := t.TempDir()
	if err := Init(tmp, "", ""); err != nil {
		t.Fatalf("Init: %v", err)
	}
	notesPath := filepath.Join(tmp, ".tekhton")
	_ = os.MkdirAll(notesPath, 0o755)
	notesFile := filepath.Join(notesPath, "HUMAN_NOTES.md")
	_ = os.WriteFile(notesFile, []byte("# Notes\n\nNo items.\n"), 0o644)

	e := &Emitter{
		ProjectDir:     tmp,
		DashDir:        filepath.Join(tmp, ".claude", "dashboard"),
		Enabled:        true,
		HumanNotesFile: notesFile,
		Now:            fixedTime,
	}
	if err := e.EmitNotes(); err != nil {
		t.Fatalf("EmitNotes: %v", err)
	}
	body, _ := os.ReadFile(filepath.Join(e.DashDir, "data", "notes.js"))
	if !strings.Contains(string(body), "window.TK_NOTES = []") {
		t.Fatalf("empty notes should emit bare array; got: %s", body)
	}
}

func TestEmitNotes_ParsesMetadata(t *testing.T) {
	tmp := t.TempDir()
	if err := Init(tmp, "", ""); err != nil {
		t.Fatalf("Init: %v", err)
	}
	notesDir := filepath.Join(tmp, ".tekhton")
	_ = os.MkdirAll(notesDir, 0o755)
	notesFile := filepath.Join(notesDir, "HUMAN_NOTES.md")
	body := `# Notes

- [ ] [BUG] Fix login flow <!-- note:bug001 created:2026-05-29 priority:high -->
  > The login form crashes when email contains special chars.

- [x] [FEAT] Add export to PDF <!-- note:feat002 created:2026-05-28 acceptance:passed -->
`
	_ = os.WriteFile(notesFile, []byte(body), 0o644)

	e := &Emitter{
		ProjectDir:     tmp,
		DashDir:        filepath.Join(tmp, ".claude", "dashboard"),
		Enabled:        true,
		HumanNotesFile: notesFile,
		Now:            fixedTime,
	}
	if err := e.EmitNotes(); err != nil {
		t.Fatalf("EmitNotes: %v", err)
	}
	emitted, _ := os.ReadFile(filepath.Join(e.DashDir, "data", "notes.js"))
	out := string(emitted)
	for _, want := range []string{"bug001", "BUG", "Fix login flow", "high", "feat002", "FEAT"} {
		if !strings.Contains(out, want) {
			t.Errorf("notes.js missing %q\nfull body:\n%s", want, out)
		}
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
