// Package dashboard owns the Watchtower data-file emit chain.
//
// The Watchtower dashboard is a static HTML page (templates/watchtower/)
// served from the project's .claude/dashboard/ directory. It loads 10 JS
// data files via <script> tags; each file is a JSON payload wrapped in
// `window.<TK_VAR> = <json>;` scaffolding.
//
// The Python sidecar (tools/tui.py is unrelated; the Watchtower equivalent
// is the browser tab) and the browser itself poll these files on a sub-
// second cadence. A non-atomic write would let the reader observe a
// partial file; this package writes via tempfile + os.Rename for every
// write, no exceptions.

package dashboard

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"time"
)

// jsFileTimeFunc is the injected clock used for the `// Updated:` header
// line in generated files. The parity gate normalizes this line before
// diffing, so a fixed-time test override is the production-correct path.
type jsFileTimeFunc func() time.Time

// WriteJSFile marshals payload to JSON, wraps it in the standard JS
// scaffold (`// header\nwindow.<varname> = <json>;\n`), and writes via
// tempfile + os.Rename so a reader on the static-site side never observes
// a partial file. The time source is injected so tests can produce a fixed
// `// Updated:` header for golden-file comparisons.
func WriteJSFile(path, varname string, payload any, now jsFileTimeFunc) error {
	if path == "" {
		return fmt.Errorf("WriteJSFile: empty path")
	}
	if varname == "" {
		return fmt.Errorf("WriteJSFile: empty varname")
	}
	if now == nil {
		now = time.Now
	}
	data, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("WriteJSFile %s: marshal: %w", path, err)
	}
	ts := now().UTC().Format("2006-01-02T15:04:05Z")
	body := fmt.Sprintf(
		"// Generated by Tekhton Watchtower — do not edit\n// Updated: %s\nwindow.%s = %s;\n",
		ts, varname, data,
	)
	return atomicWriteFile(path, []byte(body))
}

// WriteJSRaw is the raw-JSON variant: payload is already a marshalled JSON
// blob (e.g. timeline events that must pass through byte-for-byte). Skips
// the json.Marshal step.
func WriteJSRaw(path, varname string, rawJSON []byte, now jsFileTimeFunc) error {
	if path == "" {
		return fmt.Errorf("WriteJSRaw: empty path")
	}
	if varname == "" {
		return fmt.Errorf("WriteJSRaw: empty varname")
	}
	if now == nil {
		now = time.Now
	}
	ts := now().UTC().Format("2006-01-02T15:04:05Z")
	body := fmt.Sprintf(
		"// Generated by Tekhton Watchtower — do not edit\n// Updated: %s\nwindow.%s = %s;\n",
		ts, varname, rawJSON,
	)
	return atomicWriteFile(path, []byte(body))
}

// atomicWriteFile is the tempfile+rename helper. Mirrors the
// internal/tui/state.go::SaveAtomic pattern.
func atomicWriteFile(path string, body []byte) error {
	suffix, err := randSuffix()
	if err != nil {
		return fmt.Errorf("atomicWriteFile %s: rand: %w", path, err)
	}
	tmp := path + ".tmp." + suffix
	if err := os.WriteFile(tmp, body, 0o644); err != nil {
		return fmt.Errorf("atomicWriteFile %s: write tmp: %w", path, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("atomicWriteFile %s: rename: %w", path, err)
	}
	return nil
}

// randSuffix returns 8 hex chars of entropy for the tempfile name. Avoids
// importing the wider math/rand machinery for a one-liner.
func randSuffix() (string, error) {
	var b [4]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	return hex.EncodeToString(b[:]), nil
}
